[tox]
isolated_build = True
envlist = py310,py311,py312,py313,py314

[testenv]
deps =
    black
    coverage
    mypy
    pylint
    pytest
commands =
    black src/dicebear
    pylint src/dicebear --exit-zero
;    mypy src/dicebear
    coverage erase
    coverage run --include=src/dicebear/* -m pytest -ra
    coverage report -m

[flake8]
count = True
format = pylint
max-line-length = 120
indent-size = 4
