# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Adventurer(StyleBase):
    _name = "adventurer"

    class Details(Enum):
        BIRTHMARK = "birthmark"
        BLUSH = "blush"
        FRECKLES = "freckles"
        MUSTACHE = "mustache"

    class Earrings(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"

    class Eyebrows(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"
        VARIANT26 = "variant26"

    class Glasses(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"

    class Hair(Enum):
        LONG01 = "long01"
        LONG02 = "long02"
        LONG03 = "long03"
        LONG04 = "long04"
        LONG05 = "long05"
        LONG06 = "long06"
        LONG07 = "long07"
        LONG08 = "long08"
        LONG09 = "long09"
        LONG10 = "long10"
        LONG11 = "long11"
        LONG12 = "long12"
        LONG13 = "long13"
        LONG14 = "long14"
        LONG15 = "long15"
        LONG16 = "long16"
        LONG17 = "long17"
        LONG18 = "long18"
        LONG19 = "long19"
        LONG20 = "long20"
        LONG21 = "long21"
        LONG22 = "long22"
        LONG23 = "long23"
        LONG24 = "long24"
        LONG25 = "long25"
        LONG26 = "long26"
        SHORT01 = "short01"
        SHORT02 = "short02"
        SHORT03 = "short03"
        SHORT04 = "short04"
        SHORT05 = "short05"
        SHORT06 = "short06"
        SHORT07 = "short07"
        SHORT08 = "short08"
        SHORT09 = "short09"
        SHORT10 = "short10"
        SHORT11 = "short11"
        SHORT12 = "short12"
        SHORT13 = "short13"
        SHORT14 = "short14"
        SHORT15 = "short15"
        SHORT16 = "short16"
        SHORT17 = "short17"
        SHORT18 = "short18"
        SHORT19 = "short19"

    class Head(Enum):
        DEFAULT = "default"

    class Mouth(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"
        VARIANT26 = "variant26"
        VARIANT27 = "variant27"
        VARIANT28 = "variant28"
        VARIANT29 = "variant29"
        VARIANT30 = "variant30"

    class HairColor(Enum):
        C0E0E0E = "#0e0e0e"
        CE5D7A3 = "#e5d7a3"
        CB9A05F = "#b9a05f"
        C796A45 = "#796a45"
        C85C2C6 = "#85c2c6"
        C6A4E35 = "#6a4e35"
        C562306 = "#562306"
        CAFAFAF = "#afafaf"
        C3EAC2C = "#3eac2c"
        CDBA3BE = "#dba3be"
        C592454 = "#592454"
        CAC6511 = "#ac6511"
        CCB6820 = "#cb6820"
        CAB2A18 = "#ab2a18"

    class SkinColor(Enum):
        CF2D3B1 = "#f2d3b1"
        CECAD80 = "#ecad80"
        C9E5622 = "#9e5622"
        C763900 = "#763900"

    def __init__(
            self,
            details: Details | str | None = None,
            detailsProbability: int | None = None,
            earrings: Earrings | str | None = None,
            earringsProbability: int | None = None,
            eyebrows: Eyebrows | str | None = None,
            eyes: Eyes | str | None = None,
            glasses: Glasses | str | None = None,
            glassesProbability: int | None = None,
            hair: Hair | str | None = None,
            head: Head | str | None = None,
            mouth: Mouth | str | None = None,
            hairColor: HairColor | str | None = None,
            skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            details=details,
            detailsProbability=detailsProbability,
            earrings=earrings,
            earringsProbability=earringsProbability,
            eyebrows=eyebrows,
            eyes=eyes,
            glasses=glasses,
            glassesProbability=glassesProbability,
            hair=hair,
            head=head,
            mouth=mouth,
            hairColor=hairColor,
            skinColor=skinColor,
        )
