# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/adventurer-neutral.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("AdventurerNeutral",)


@dataclass
class AdventurerNeutral(StyleBase):
    style_name: ClassVar[str] = "adventurer-neutral"

    eyebrows: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (10 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (21 more)
    glasses: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05
    mouth: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (25 more)
