# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/adventurer.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase
from ..models import DColor

__all__ = ("Adventurer",)


@dataclass
class Adventurer(StyleBase):
    style_name: ClassVar[str] = "adventurer"

    details: Optional[List[str]] = None  # birthmark, blush, freckles, mustache
    earrings: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (1 more)
    eyebrows: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (10 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (21 more)
    glasses: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05
    hair: Optional[List[str]] = None  # long01, long02, long03, long04, long05, ... (40 more)
    head: Optional[List[str]] = None  # default
    mouth: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (25 more)

    hairColor: Optional[DColor] = None  # 0e0e0e, e5d7a3, b9a05f, 796a45, 85c2c6, ... (9 more)
    skinColor: Optional[DColor] = None  # f2d3b1, ecad80, 9e5622, 763900
