# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Avataaars(StyleBase):
    _name = "avataaars"

    class Accessories(Enum):
        EYEPATCH = "eyepatch"
        KURT = "kurt"
        PRESCRIPTION01 = "prescription01"
        PRESCRIPTION02 = "prescription02"
        ROUND = "round"
        SUNGLASSES = "sunglasses"
        WAYFARERS = "wayfarers"

    class Clothes(Enum):
        BLAZER_AND_SHIRT = "blazerAndShirt"
        BLAZER_AND_SWEATER = "blazerAndSweater"
        COLLAR_AND_SWEATER = "collarAndSweater"
        GRAPHIC_SHIRT = "graphicShirt"
        HOODIE = "hoodie"
        OVERALL = "overall"
        SHIRT_CREW_NECK = "shirtCrewNeck"
        SHIRT_SCOOP_NECK = "shirtScoopNeck"
        SHIRT_VNECK = "shirtVNeck"

    class ClothesGraphic(Enum):
        BAT = "bat"
        BEAR = "bear"
        CUMBIA = "cumbia"
        DEER = "deer"
        DIAMOND = "diamond"
        HOLA = "hola"
        PIZZA = "pizza"
        RESIST = "resist"
        SKULL = "skull"
        SKULL_OUTLINE = "skullOutline"

    class Eyebrows(Enum):
        ANGRY = "angry"
        ANGRY_NATURAL = "angryNatural"
        DEFAULT = "default"
        DEFAULT_NATURAL = "defaultNatural"
        FLAT_NATURAL = "flatNatural"
        FROWN_NATURAL = "frownNatural"
        RAISED_EXCITED = "raisedExcited"
        RAISED_EXCITED_NATURAL = "raisedExcitedNatural"
        SAD_CONCERNED = "sadConcerned"
        SAD_CONCERNED_NATURAL = "sadConcernedNatural"
        UNIBROW_NATURAL = "unibrowNatural"
        UP_DOWN = "upDown"
        UP_DOWN_NATURAL = "upDownNatural"

    class Eyes(Enum):
        CLOSED = "closed"
        CRY = "cry"
        DEFAULT = "default"
        EYE_ROLL = "eyeRoll"
        HAPPY = "happy"
        HEARTS = "hearts"
        SIDE = "side"
        SQUINT = "squint"
        SURPRISED = "surprised"
        WINK = "wink"
        WINK_WACKY = "winkWacky"
        X_DIZZY = "xDizzy"

    class FacialHair(Enum):
        BEARD_LIGHT = "beardLight"
        BEARD_MAJESTIC = "beardMajestic"
        BEARD_MEDIUM = "beardMedium"
        MOUSTACHE_FANCY = "moustacheFancy"
        MOUSTACHE_MAGNUM = "moustacheMagnum"

    class Mouth(Enum):
        CONCERNED = "concerned"
        DEFAULT = "default"
        DISBELIEF = "disbelief"
        EATING = "eating"
        GRIMACE = "grimace"
        SAD = "sad"
        SCREAM_OPEN = "screamOpen"
        SERIOUS = "serious"
        SMILE = "smile"
        TONGUE = "tongue"
        TWINKLE = "twinkle"
        VOMIT = "vomit"

    class Nose(Enum):
        DEFAULT = "default"

    class Top(Enum):
        BIG_HAIR = "bigHair"
        BOB = "bob"
        BUN = "bun"
        CURLY = "curly"
        CURVY = "curvy"
        DREADS = "dreads"
        DREADS01 = "dreads01"
        DREADS02 = "dreads02"
        FRIDA = "frida"
        FRIZZLE = "frizzle"
        FRO = "fro"
        FRO_BAND = "froBand"
        HAT = "hat"
        HIJAB = "hijab"
        LONG_BUT_NOT_TOO_LONG = "longButNotTooLong"
        MIA_WALLACE = "miaWallace"
        SHAGGY = "shaggy"
        SHAGGY_MULLET = "shaggyMullet"
        SHAVED_SIDES = "shavedSides"
        SHORT_CURLY = "shortCurly"
        SHORT_FLAT = "shortFlat"
        SHORT_ROUND = "shortRound"
        SHORT_WAVED = "shortWaved"
        SIDES = "sides"
        STRAIGHT01 = "straight01"
        STRAIGHT02 = "straight02"
        STRAIGHT_AND_STRAND = "straightAndStrand"
        THE_CAESAR = "theCaesar"
        THE_CAESAR_AND_SIDE_PART = "theCaesarAndSidePart"
        TURBAN = "turban"
        WINTER_HAT02 = "winterHat02"
        WINTER_HAT03 = "winterHat03"
        WINTER_HAT04 = "winterHat04"
        WINTER_HAT1 = "winterHat1"

    class AccessoriesColor(Enum):
        C262E33 = "#262e33"
        C65C9FF = "#65c9ff"
        C5199E4 = "#5199e4"
        C25557C = "#25557c"
        CE6E6E6 = "#e6e6e6"
        C929598 = "#929598"
        C3C4F5C = "#3c4f5c"
        CB1E2FF = "#b1e2ff"
        CA7FFC4 = "#a7ffc4"
        CFFDEB5 = "#ffdeb5"
        CFFAFB9 = "#ffafb9"
        CFFFFB1 = "#ffffb1"
        CFF488E = "#ff488e"
        CFF5C5C = "#ff5c5c"
        CFFFFFF = "#ffffff"

    class ClothesColor(Enum):
        C262E33 = "#262e33"
        C65C9FF = "#65c9ff"
        C5199E4 = "#5199e4"
        C25557C = "#25557c"
        CE6E6E6 = "#e6e6e6"
        C929598 = "#929598"
        C3C4F5C = "#3c4f5c"
        CB1E2FF = "#b1e2ff"
        CA7FFC4 = "#a7ffc4"
        CFFAFB9 = "#ffafb9"
        CFFFFB1 = "#ffffb1"
        CFF488E = "#ff488e"
        CFF5C5C = "#ff5c5c"
        CFFFFFF = "#ffffff"

    class FacialHairColor(Enum):
        CA55728 = "#a55728"
        C2C1B18 = "#2c1b18"
        CB58143 = "#b58143"
        CD6B370 = "#d6b370"
        C724133 = "#724133"
        C4A312C = "#4a312c"
        CF59797 = "#f59797"
        CECDCBF = "#ecdcbf"
        CC93305 = "#c93305"
        CE8E1E1 = "#e8e1e1"

    class HairColor(Enum):
        CA55728 = "#a55728"
        C2C1B18 = "#2c1b18"
        CB58143 = "#b58143"
        CD6B370 = "#d6b370"
        C724133 = "#724133"
        C4A312C = "#4a312c"
        CF59797 = "#f59797"
        CECDCBF = "#ecdcbf"
        CC93305 = "#c93305"
        CE8E1E1 = "#e8e1e1"

    class HatColor(Enum):
        C262E33 = "#262e33"
        C65C9FF = "#65c9ff"
        C5199E4 = "#5199e4"
        C25557C = "#25557c"
        CE6E6E6 = "#e6e6e6"
        C929598 = "#929598"
        C3C4F5C = "#3c4f5c"
        CB1E2FF = "#b1e2ff"
        CA7FFC4 = "#a7ffc4"
        CFFDEB5 = "#ffdeb5"
        CFFAFB9 = "#ffafb9"
        CFFFFB1 = "#ffffb1"
        CFF488E = "#ff488e"
        CFF5C5C = "#ff5c5c"
        CFFFFFF = "#ffffff"

    class SkinColor(Enum):
        C614335 = "#614335"
        CD08B5B = "#d08b5b"
        CAE5D29 = "#ae5d29"
        CEDB98A = "#edb98a"
        CFFDBB4 = "#ffdbb4"
        CFD9841 = "#fd9841"
        CF8D25C = "#f8d25c"

    def __init__(
            self,
            accessories: Accessories | str | None = None,
            accessoriesProbability: int | None = None,
            clothes: Clothes | str | None = None,
            clothesGraphic: ClothesGraphic | str | None = None,
            eyebrows: Eyebrows | str | None = None,
            eyes: Eyes | str | None = None,
            facialHair: FacialHair | str | None = None,
            facialHairProbability: int | None = None,
            mouth: Mouth | str | None = None,
            nose: Nose | str | None = None,
            top: Top | str | None = None,
            topProbability: int | None = None,
            accessoriesColor: AccessoriesColor | str | None = None,
            clothesColor: ClothesColor | str | None = None,
            facialHairColor: FacialHairColor | str | None = None,
            hairColor: HairColor | str | None = None,
            hatColor: HatColor | str | None = None,
            skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            accessories=accessories,
            accessoriesProbability=accessoriesProbability,
            clothes=clothes,
            clothesGraphic=clothesGraphic,
            eyebrows=eyebrows,
            eyes=eyes,
            facialHair=facialHair,
            facialHairProbability=facialHairProbability,
            mouth=mouth,
            nose=nose,
            top=top,
            topProbability=topProbability,
            accessoriesColor=accessoriesColor,
            clothesColor=clothesColor,
            facialHairColor=facialHairColor,
            hairColor=hairColor,
            hatColor=hatColor,
            skinColor=skinColor,
        )
