# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/avataaars.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Avataaars",)


@dataclass
class Avataaars(StyleBase):
    style_name: ClassVar[str] = "avataaars"

    accessories: Optional[List[str]] = None  # eyepatch, kurt, prescription01, prescription02, round, ... (2 more)
    clothes: Optional[List[str]] = None  # blazerAndShirt, blazerAndSweater, collarAndSweater, graphicShirt, hoodie, ... (4 more)
    clothesGraphic: Optional[List[str]] = None  # bat, bear, cumbia, deer, diamond, ... (5 more)
    eyebrows: Optional[List[str]] = None  # angry, angryNatural, default, defaultNatural, flatNatural, ... (8 more)
    eyes: Optional[List[str]] = None  # closed, cry, default, eyeRoll, happy, ... (7 more)
    facialHair: Optional[List[str]] = None  # beardLight, beardMajestic, beardMedium, moustacheFancy, moustacheMagnum
    mouth: Optional[List[str]] = None  # concerned, default, disbelief, eating, grimace, ... (7 more)
    nose: Optional[List[str]] = None  # default
    top: Optional[List[str]] = None  # bigHair, bob, bun, curly, curvy, ... (29 more)

    accessoriesColor: Optional[DColor] = None  # 262e33, 65c9ff, 5199e4, 25557c, e6e6e6, ... (10 more)
    clothesColor: Optional[DColor] = None  # 262e33, 65c9ff, 5199e4, 25557c, e6e6e6, ... (9 more)
    facialHairColor: Optional[DColor] = None  # a55728, 2c1b18, b58143, d6b370, 724133, ... (5 more)
    hairColor: Optional[DColor] = None  # a55728, 2c1b18, b58143, d6b370, 724133, ... (5 more)
    hatColor: Optional[DColor] = None  # 262e33, 65c9ff, 5199e4, 25557c, e6e6e6, ... (10 more)
    skinColor: Optional[DColor] = None  # 614335, d08b5b, ae5d29, edb98a, ffdbb4, ... (2 more)
