# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class AvataaarsNeutral(StyleBase):
    _name = "avataaars-neutral"

    class Eyebrows(Enum):
        ANGRY = "angry"
        ANGRY_NATURAL = "angryNatural"
        DEFAULT = "default"
        DEFAULT_NATURAL = "defaultNatural"
        FLAT_NATURAL = "flatNatural"
        FROWN_NATURAL = "frownNatural"
        RAISED_EXCITED = "raisedExcited"
        RAISED_EXCITED_NATURAL = "raisedExcitedNatural"
        SAD_CONCERNED = "sadConcerned"
        SAD_CONCERNED_NATURAL = "sadConcernedNatural"
        UNIBROW_NATURAL = "unibrowNatural"
        UP_DOWN = "upDown"
        UP_DOWN_NATURAL = "upDownNatural"

    class Eyes(Enum):
        CLOSED = "closed"
        CRY = "cry"
        DEFAULT = "default"
        EYE_ROLL = "eyeRoll"
        HAPPY = "happy"
        HEARTS = "hearts"
        SIDE = "side"
        SQUINT = "squint"
        SURPRISED = "surprised"
        WINK = "wink"
        WINK_WACKY = "winkWacky"
        X_DIZZY = "xDizzy"

    class Mouth(Enum):
        CONCERNED = "concerned"
        DEFAULT = "default"
        DISBELIEF = "disbelief"
        EATING = "eating"
        GRIMACE = "grimace"
        SAD = "sad"
        SCREAM_OPEN = "screamOpen"
        SERIOUS = "serious"
        SMILE = "smile"
        TONGUE = "tongue"
        TWINKLE = "twinkle"
        VOMIT = "vomit"

    class Nose(Enum):
        DEFAULT = "default"

    def __init__(
            self,
            eyebrows: Eyebrows | str | None = None,
            eyes: Eyes | str | None = None,
            mouth: Mouth | str | None = None,
            nose: Nose | str | None = None,
    ) -> None:
        super().__init__(
            eyebrows=eyebrows,
            eyes=eyes,
            mouth=mouth,
            nose=nose,
        )
