# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/avataaars-neutral.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("AvataaarsNeutral",)


@dataclass
class AvataaarsNeutral(StyleBase):
    style_name: ClassVar[str] = "avataaars-neutral"

    eyebrows: Optional[List[str]] = None  # angry, angryNatural, default, defaultNatural, flatNatural, ... (8 more)
    eyes: Optional[List[str]] = None  # closed, cry, default, eyeRoll, happy, ... (7 more)
    mouth: Optional[List[str]] = None  # concerned, default, disbelief, eating, grimace, ... (7 more)
    nose: Optional[List[str]] = None  # default
