# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/big-smile.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("BigSmile",)


@dataclass
class BigSmile(StyleBase):
    style_name: ClassVar[str] = "big-smile"

    accessories: Optional[List[str]] = None  # catEars, clownNose, faceMask, glasses, mustache, ... (3 more)
    eyes: Optional[List[str]] = None  # angry, cheery, confused, normal, sad, ... (3 more)
    hair: Optional[List[str]] = None  # bangs, bowlCutHair, braids, bunHair, curlyBob, ... (8 more)
    head: Optional[List[str]] = None  # base
    mouth: Optional[List[str]] = None  # awkwardSmile, braces, gapSmile, kawaii, openSad, ... (3 more)

    hairColor: Optional[DColor] = None  # 220f00, 3a1a00, 71472d, e2ba87, 605de4, ... (3 more)
    skinColor: Optional[DColor] = None  # ffe4c0, f5d7b1, efcc9f, e2ba87, c99c62, ... (3 more)
