# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/big-ears-neutral.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("BigEarsNeutral",)


@dataclass
class BigEarsNeutral(StyleBase):
    style_name: ClassVar[str] = "big-ears-neutral"

    details: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (1 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (27 more)
    mouth: Optional[List[str]] = None  # variant0101, variant0102, variant0103, variant0104, variant0105, ... (33 more)
    nose: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (7 more)
