# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/big-ears.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("BigEars",)


@dataclass
class BigEars(StyleBase):
    style_name: ClassVar[str] = "big-ears"

    details: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (1 more)
    ears: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (3 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (27 more)
    frontHair: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (7 more)
    hair: Optional[List[str]] = None  # long01, long02, long03, long04, long05, ... (35 more)
    head: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (5 more)
    mouth: Optional[List[str]] = None  # variant0101, variant0102, variant0103, variant0104, variant0105, ... (33 more)
    nose: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (7 more)
    sideburns: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (2 more)

    hairColor: Optional[DColor] = None  # 2c1b18, e8e1e1, ecdcbf, d6b370, f59797, ... (5 more)
    skinColor: Optional[DColor] = None  # f8b788, da9969, c07f50, a66637, 89532c
