# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class BigSmile(StyleBase):
    _name = "big-smile"

    class Accessories(Enum):
        CAT_EARS = "catEars"
        CLOWN_NOSE = "clownNose"
        FACE_MASK = "faceMask"
        GLASSES = "glasses"
        MUSTACHE = "mustache"
        SAILORMOON_CROWN = "sailormoonCrown"
        SLEEP_MASK = "sleepMask"
        SUNGLASSES = "sunglasses"

    class Eyes(Enum):
        ANGRY = "angry"
        CHEERY = "cheery"
        CONFUSED = "confused"
        NORMAL = "normal"
        SAD = "sad"
        SLEEPY = "sleepy"
        STARSTRUCK = "starstruck"
        WINKING = "winking"

    class Hair(Enum):
        BANGS = "bangs"
        BOWL_CUT_HAIR = "bowlCutHair"
        BRAIDS = "braids"
        BUN_HAIR = "bunHair"
        CURLY_BOB = "curlyBob"
        CURLY_SHORT_HAIR = "curlyShortHair"
        FRO_BUN = "froBun"
        HALF_SHAVED_HEAD = "halfShavedHead"
        MOHAWK = "mohawk"
        SHAVED_HEAD = "shavedHead"
        SHORT_HAIR = "shortHair"
        STRAIGHT_HAIR = "straightHair"
        WAVY_BOB = "wavyBob"

    class Head(Enum):
        BASE = "base"

    class Mouth(Enum):
        AWKWARD_SMILE = "awkwardSmile"
        BRACES = "braces"
        GAP_SMILE = "gapSmile"
        KAWAII = "kawaii"
        OPEN_SAD = "openSad"
        OPENED_SMILE = "openedSmile"
        TEETH_SMILE = "teethSmile"
        UNIMPRESSED = "unimpressed"

    class HairColor(Enum):
        C220F00 = "#220f00"
        C3A1A00 = "#3a1a00"
        C71472D = "#71472d"
        CE2BA87 = "#e2ba87"
        C605DE4 = "#605de4"
        C238D80 = "#238d80"
        CD56C0C = "#d56c0c"
        CE9B729 = "#e9b729"

    class SkinColor(Enum):
        CFFE4C0 = "#ffe4c0"
        CF5D7B1 = "#f5d7b1"
        CEFCC9F = "#efcc9f"
        CE2BA87 = "#e2ba87"
        CC99C62 = "#c99c62"
        CA47539 = "#a47539"
        C8C5A2B = "#8c5a2b"
        C643D19 = "#643d19"

    def __init__(
        self,
        accessories: Accessories | str | None = None,
        accessoriesProbability: int | None = None,
        eyes: Eyes | str | None = None,
        hair: Hair | str | None = None,
        head: Head | str | None = None,
        mouth: Mouth | str | None = None,
        hairColor: HairColor | str | None = None,
        skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            accessories=accessories,
            accessoriesProbability=accessoriesProbability,
            eyes=eyes,
            hair=hair,
            head=head,
            mouth=mouth,
            hairColor=hairColor,
            skinColor=skinColor,
        )
