# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class BigEars(StyleBase):
    _name = "big-ears"

    class Details(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"

    class Ears(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"
        VARIANT26 = "variant26"
        VARIANT27 = "variant27"
        VARIANT28 = "variant28"
        VARIANT29 = "variant29"
        VARIANT30 = "variant30"
        VARIANT31 = "variant31"
        VARIANT32 = "variant32"

    class FrontHair(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"

    class Hair(Enum):
        LONG01 = "long01"
        LONG02 = "long02"
        LONG03 = "long03"
        LONG04 = "long04"
        LONG05 = "long05"
        LONG06 = "long06"
        LONG07 = "long07"
        LONG08 = "long08"
        LONG09 = "long09"
        LONG10 = "long10"
        LONG11 = "long11"
        LONG12 = "long12"
        LONG13 = "long13"
        LONG14 = "long14"
        LONG15 = "long15"
        LONG16 = "long16"
        LONG17 = "long17"
        LONG18 = "long18"
        LONG19 = "long19"
        LONG20 = "long20"
        SHORT01 = "short01"
        SHORT02 = "short02"
        SHORT03 = "short03"
        SHORT04 = "short04"
        SHORT05 = "short05"
        SHORT06 = "short06"
        SHORT07 = "short07"
        SHORT08 = "short08"
        SHORT09 = "short09"
        SHORT10 = "short10"
        SHORT11 = "short11"
        SHORT12 = "short12"
        SHORT13 = "short13"
        SHORT14 = "short14"
        SHORT15 = "short15"
        SHORT16 = "short16"
        SHORT17 = "short17"
        SHORT18 = "short18"
        SHORT19 = "short19"
        SHORT20 = "short20"

    class Head(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"

    class Mouth(Enum):
        VARIANT0101 = "variant0101"
        VARIANT0102 = "variant0102"
        VARIANT0103 = "variant0103"
        VARIANT0104 = "variant0104"
        VARIANT0105 = "variant0105"
        VARIANT0201 = "variant0201"
        VARIANT0202 = "variant0202"
        VARIANT0203 = "variant0203"
        VARIANT0204 = "variant0204"
        VARIANT0205 = "variant0205"
        VARIANT0301 = "variant0301"
        VARIANT0302 = "variant0302"
        VARIANT0303 = "variant0303"
        VARIANT0304 = "variant0304"
        VARIANT0305 = "variant0305"
        VARIANT0401 = "variant0401"
        VARIANT0402 = "variant0402"
        VARIANT0403 = "variant0403"
        VARIANT0404 = "variant0404"
        VARIANT0405 = "variant0405"
        VARIANT0501 = "variant0501"
        VARIANT0502 = "variant0502"
        VARIANT0503 = "variant0503"
        VARIANT0504 = "variant0504"
        VARIANT0505 = "variant0505"
        VARIANT0601 = "variant0601"
        VARIANT0602 = "variant0602"
        VARIANT0603 = "variant0603"
        VARIANT0604 = "variant0604"
        VARIANT0605 = "variant0605"
        VARIANT0701 = "variant0701"
        VARIANT0702 = "variant0702"
        VARIANT0703 = "variant0703"
        VARIANT0704 = "variant0704"
        VARIANT0705 = "variant0705"
        VARIANT0706 = "variant0706"
        VARIANT0707 = "variant0707"
        VARIANT0708 = "variant0708"

    class Nose(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"

    class Sideburns(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"

    class HairColor(Enum):
        C2C1B18 = "#2c1b18"
        CE8E1E1 = "#e8e1e1"
        CECDCBF = "#ecdcbf"
        CD6B370 = "#d6b370"
        CF59797 = "#f59797"
        CB58143 = "#b58143"
        CA55728 = "#a55728"
        C724133 = "#724133"
        C4A312C = "#4a312c"
        CC93305 = "#c93305"

    class SkinColor(Enum):
        CF8B788 = "#f8b788"
        CDA9969 = "#da9969"
        CC07F50 = "#c07f50"
        CA66637 = "#a66637"
        C89532C = "#89532c"

    def __init__(
            self,
            details: Details | str | None = None,
            detailsProbability: int | None = None,
            ears: Ears | str | None = None,
            eyes: Eyes | str | None = None,
            frontHair: FrontHair | str | None = None,
            hair: Hair | str | None = None,
            head: Head | str | None = None,
            mouth: Mouth | str | None = None,
            nose: Nose | str | None = None,
            sideburns: Sideburns | str | None = None,
            hairColor: HairColor | str | None = None,
            skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            details=details,
            detailsProbability=detailsProbability,
            ears=ears,
            eyes=eyes,
            frontHair=frontHair,
            hair=hair,
            head=head,
            mouth=mouth,
            nose=nose,
            sideburns=sideburns,
            hairColor=hairColor,
            skinColor=skinColor,
        )
