# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/bottts.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Bottts",)


@dataclass
class Bottts(StyleBase):
    style_name: ClassVar[str] = "bottts"

    eyes: Optional[List[str]] = None  # bulging, dizzy, eva, frame1, frame2, ... (9 more)
    head: Optional[List[str]] = None  # round01, round02, square01, square02, square03, ... (1 more)
    mouth: Optional[List[str]] = None  # bite, diagram, grill01, grill02, grill03, ... (4 more)
    sides: Optional[List[str]] = None  # antenna01, antenna02, cables01, cables02, round, ... (2 more)
    texture: Optional[List[str]] = None  # camo01, camo02, circuits, dirty01, dirty02, ... (3 more)
    top: Optional[List[str]] = None  # antenna, antennaCrooked, bulb01, glowingBulb01, glowingBulb02, ... (4 more)

    baseColor: Optional[DColor] = None  # e45e4d, de6811, c67c11, b18911, 9b9312, ... (17 more)
