# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class BotttsNeutral(StyleBase):
    _name = "bottts-neutral"

    class Eyes(Enum):
        BULGING = "bulging"
        DIZZY = "dizzy"
        EVA = "eva"
        FRAME1 = "frame1"
        FRAME2 = "frame2"
        GLOW = "glow"
        HAPPY = "happy"
        HEARTS = "hearts"
        ROBOCOP = "robocop"
        ROUND = "round"
        ROUND_FRAME01 = "roundFrame01"
        ROUND_FRAME02 = "roundFrame02"
        SENSOR = "sensor"
        SHADE01 = "shade01"

    class Mouth(Enum):
        BITE = "bite"
        DIAGRAM = "diagram"
        GRILL01 = "grill01"
        GRILL02 = "grill02"
        GRILL03 = "grill03"
        SMILE01 = "smile01"
        SMILE02 = "smile02"
        SQUARE01 = "square01"
        SQUARE02 = "square02"

    class Texture(Enum):
        CAMO01 = "camo01"
        CAMO02 = "camo02"
        CIRCUITS = "circuits"
        DIRTY01 = "dirty01"
        DIRTY02 = "dirty02"
        DOTS = "dots"
        GRUNGE01 = "grunge01"
        GRUNGE02 = "grunge02"

    def __init__(
            self,
            eyes: Eyes | str | None = None,
            mouth: Mouth | str | None = None,
            texture: Texture | str | None = None,
            textureProbability: int | None = None,
    ) -> None:
        super().__init__(
            eyes=eyes,
            mouth=mouth,
            texture=texture,
            textureProbability=textureProbability,
        )
