# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Bottts(StyleBase):
    _name = "bottts"

    class Eyes(Enum):
        BULGING = "bulging"
        DIZZY = "dizzy"
        EVA = "eva"
        FRAME1 = "frame1"
        FRAME2 = "frame2"
        GLOW = "glow"
        HAPPY = "happy"
        HEARTS = "hearts"
        ROBOCOP = "robocop"
        ROUND = "round"
        ROUND_FRAME01 = "roundFrame01"
        ROUND_FRAME02 = "roundFrame02"
        SENSOR = "sensor"
        SHADE01 = "shade01"

    class Head(Enum):
        ROUND01 = "round01"
        ROUND02 = "round02"
        SQUARE01 = "square01"
        SQUARE02 = "square02"
        SQUARE03 = "square03"
        SQUARE04 = "square04"

    class Mouth(Enum):
        BITE = "bite"
        DIAGRAM = "diagram"
        GRILL01 = "grill01"
        GRILL02 = "grill02"
        GRILL03 = "grill03"
        SMILE01 = "smile01"
        SMILE02 = "smile02"
        SQUARE01 = "square01"
        SQUARE02 = "square02"

    class Sides(Enum):
        ANTENNA01 = "antenna01"
        ANTENNA02 = "antenna02"
        CABLES01 = "cables01"
        CABLES02 = "cables02"
        ROUND = "round"
        SQUARE = "square"
        SQUARE_ASSYMETRIC = "squareAssymetric"

    class Texture(Enum):
        CAMO01 = "camo01"
        CAMO02 = "camo02"
        CIRCUITS = "circuits"
        DIRTY01 = "dirty01"
        DIRTY02 = "dirty02"
        DOTS = "dots"
        GRUNGE01 = "grunge01"
        GRUNGE02 = "grunge02"

    class Top(Enum):
        ANTENNA = "antenna"
        ANTENNA_CROOKED = "antennaCrooked"
        BULB01 = "bulb01"
        GLOWING_BULB01 = "glowingBulb01"
        GLOWING_BULB02 = "glowingBulb02"
        HORNS = "horns"
        LIGHTS = "lights"
        PYRAMID = "pyramid"
        RADAR = "radar"

    class BaseColor(Enum):
        CE45E4D = "#e45e4d"
        CDE6811 = "#de6811"
        CC67C11 = "#c67c11"
        CB18911 = "#b18911"
        C9B9312 = "#9b9312"
        C7A9F12 = "#7a9f12"
        C40A843 = "#40a843"
        C15A876 = "#15a876"
        C15A594 = "#15a594"
        C15A2A9 = "#15a2a9"
        C159FBF = "#159fbf"
        C1499DA = "#1499da"
        C448EF4 = "#448ef4"
        C7681F5 = "#7681f5"
        C9975EA = "#9975ea"
        CB46BD6 = "#b46bd6"
        CCA62BB = "#ca62bb"
        CD95C9A = "#d95c9a"
        CE25A75 = "#e25a75"
        C978D87 = "#978d87"
        C8F8F8F = "#8f8f8f"
        C879198 = "#879198"

    def __init__(
        self,
        eyes: Eyes | str | None = None,
        head: Head | str | None = None,
        mouth: Mouth | str | None = None,
        sides: Sides | str | None = None,
        texture: Texture | str | None = None,
        textureProbability: int | None = None,
        top: Top | str | None = None,
        baseColor: BaseColor | str | None = None,
    ) -> None:
        super().__init__(
            eyes=eyes,
            head=head,
            mouth=mouth,
            sides=sides,
            texture=texture,
            textureProbability=textureProbability,
            top=top,
            baseColor=baseColor,
        )
