# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/bottts-neutral.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("BotttsNeutral",)


@dataclass
class BotttsNeutral(StyleBase):
    style_name: ClassVar[str] = "bottts-neutral"

    eyes: Optional[List[str]] = None  # bulging, dizzy, eva, frame1, frame2, ... (9 more)
    mouth: Optional[List[str]] = None  # bite, diagram, grill01, grill02, grill03, ... (4 more)
    texture: Optional[List[str]] = None  # camo01, camo02, circuits, dirty01, dirty02, ... (3 more)
