# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Croodles(StyleBase):
    _name = "croodles"

    class Beard(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"

    class Head(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"

    class Mouth(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"

    class Mustache(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"

    class Nose(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"

    class Top(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"
        VARIANT26 = "variant26"
        VARIANT27 = "variant27"
        VARIANT28 = "variant28"
        VARIANT29 = "variant29"

    class BaseColor(Enum):
        CFFFFFF = "#ffffff"

    class EyepatchColor(Enum):
        C000000 = "#000000"

    class GlassesColor(Enum):
        C000000 = "#000000"

    class TopColor(Enum):
        C000000 = "#000000"
        C699BF7 = "#699bf7"
        C0FA958 = "#0fa958"
        C9747FF = "#9747ff"
        CF24E1E = "#f24e1e"
        CFFC700 = "#ffc700"

    def __init__(
        self,
        beard: Beard | str | None = None,
        beardProbability: int | None = None,
        eyes: Eyes | str | None = None,
        head: Head | str | None = None,
        mouth: Mouth | str | None = None,
        mustache: Mustache | str | None = None,
        mustacheProbability: int | None = None,
        nose: Nose | str | None = None,
        top: Top | str | None = None,
        baseColor: BaseColor | str | None = None,
        eyepatchColor: EyepatchColor | str | None = None,
        glassesColor: GlassesColor | str | None = None,
        topColor: TopColor | str | None = None,
    ) -> None:
        super().__init__(
            beard=beard,
            beardProbability=beardProbability,
            eyes=eyes,
            head=head,
            mouth=mouth,
            mustache=mustache,
            mustacheProbability=mustacheProbability,
            nose=nose,
            top=top,
            baseColor=baseColor,
            eyepatchColor=eyepatchColor,
            glassesColor=glassesColor,
            topColor=topColor,
        )
