# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/croodles.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Croodles",)


@dataclass
class Croodles(StyleBase):
    style_name: ClassVar[str] = "croodles"

    beard: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (11 more)
    head: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (3 more)
    mouth: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (13 more)
    mustache: Optional[List[str]] = None  # variant01, variant02, variant03, variant04
    nose: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (4 more)
    top: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (24 more)

    baseColor: Optional[DColor] = None  # ffffff
    eyepatchColor: Optional[DColor] = None  # 000000
    glassesColor: Optional[DColor] = None  # 000000
    topColor: Optional[DColor] = None  # 000000, 699bf7, 0fa958, 9747ff, f24e1e, ... (1 more)
