# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/croodles-neutral.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("CroodlesNeutral",)


@dataclass
class CroodlesNeutral(StyleBase):
    style_name: ClassVar[str] = "croodles-neutral"

    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (11 more)
    mouth: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (13 more)
    nose: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (4 more)

    eyepatchColor: Optional[DColor] = None  # 000000
    glassesColor: Optional[DColor] = None  # 000000
