# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Disco(StyleBase):
    _name = "disco"

    class Pattern(Enum):
        DEFAULT = "default"

    class Shape(Enum):
        CIRCLE = "circle"
        HEXAGON = "hexagon"
        PENTAGON = "pentagon"
        RECTANGLE = "rectangle"
        TRIANGLE = "triangle"

    class ShapeColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    def __init__(
        self,
        pattern: Pattern | str | None = None,
        shape: Shape | str | None = None,
        shapeColor: ShapeColor | str | None = None,
    ) -> None:
        super().__init__(
            pattern=pattern,
            shape=shape,
            shapeColor=shapeColor,
        )
