# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/disco.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Disco",)


@dataclass
class Disco(StyleBase):
    style_name: ClassVar[str] = "disco"

    pattern: Optional[List[str]] = None  # default
    shape: Optional[List[str]] = None  # circle, hexagon, pentagon, rectangle, triangle

    shapeColor: Optional[DColor] = None  # 000000, ffffff
