# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Dylan(StyleBase):
    _name = "dylan"

    class FacialHair(Enum):
        DEFAULT = "default"

    class Hair(Enum):
        BANGS = "bangs"
        BUNS = "buns"
        FLAT_TOP = "flatTop"
        FLUFFY = "fluffy"
        LONG_CURLS = "longCurls"
        PARTING = "parting"
        PLAIN = "plain"
        ROUND_BOB = "roundBob"
        SHAGGY = "shaggy"
        SHORT_CURLS = "shortCurls"
        SPIKY = "spiky"
        WAVY = "wavy"

    class Mood(Enum):
        ANGRY = "angry"
        CONFUSED = "confused"
        HAPPY = "happy"
        HOPEFUL = "hopeful"
        NEUTRAL = "neutral"
        SAD = "sad"
        SUPER_HAPPY = "superHappy"

    class HairColor(Enum):
        C000000 = "#000000"
        C1D5DFF = "#1d5dff"
        CFF543D = "#ff543d"
        CFFFFFF = "#ffffff"
        CFFF500 = "#fff500"

    class SkinColor(Enum):
        CC26450 = "#c26450"
        CFFD6C0 = "#ffd6c0"

    def __init__(
            self,
            facialHair: FacialHair | str | None = None,
            facialHairProbability: int | None = None,
            hair: Hair | str | None = None,
            mood: Mood | str | None = None,
            hairColor: HairColor | str | None = None,
            skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            facialHair=facialHair,
            facialHairProbability=facialHairProbability,
            hair=hair,
            mood=mood,
            hairColor=hairColor,
            skinColor=skinColor,
        )
