# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/dylan.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Dylan",)


@dataclass
class Dylan(StyleBase):
    style_name: ClassVar[str] = "dylan"

    facialHair: Optional[List[str]] = None  # default
    hair: Optional[List[str]] = None  # bangs, buns, flatTop, fluffy, longCurls, ... (7 more)
    mood: Optional[List[str]] = None  # angry, confused, happy, hopeful, neutral, ... (2 more)

    hairColor: Optional[DColor] = None  # 000000, 1d5dff, ff543d, ffffff, fff500
    skinColor: Optional[DColor] = None  # c26450, ffd6c0
