# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/fun-emoji.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("FunEmoji",)


@dataclass
class FunEmoji(StyleBase):
    style_name: ClassVar[str] = "fun-emoji"

    eyes: Optional[List[str]] = None  # closed, closed2, crying, cute, glasses, ... (10 more)
    mouth: Optional[List[str]] = None  # cute, drip, faceMask, kissHeart, lilSmile, ... (10 more)
