# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class FunEmoji(StyleBase):
    _name = "fun-emoji"

    class Eyes(Enum):
        CLOSED = "closed"
        CLOSED2 = "closed2"
        CRYING = "crying"
        CUTE = "cute"
        GLASSES = "glasses"
        LOVE = "love"
        PISSED = "pissed"
        PLAIN = "plain"
        SAD = "sad"
        SHADES = "shades"
        SLEEP_CLOSE = "sleepClose"
        STARS = "stars"
        TEAR_DROP = "tearDrop"
        WINK = "wink"
        WINK2 = "wink2"

    class Mouth(Enum):
        CUTE = "cute"
        DRIP = "drip"
        FACE_MASK = "faceMask"
        KISS_HEART = "kissHeart"
        LIL_SMILE = "lilSmile"
        PISSED = "pissed"
        PLAIN = "plain"
        SAD = "sad"
        SHOUT = "shout"
        SHY = "shy"
        SICK = "sick"
        SMILE_LOL = "smileLol"
        SMILE_TEETH = "smileTeeth"
        TONGUE_OUT = "tongueOut"
        WIDE_SMILE = "wideSmile"

    def __init__(
        self,
        eyes: Eyes | str | None = None,
        mouth: Mouth | str | None = None,
    ) -> None:
        super().__init__(
            eyes=eyes,
            mouth=mouth,
        )
