# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/glass.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("Glass",)


@dataclass
class Glass(StyleBase):
    style_name: ClassVar[str] = "glass"

    shape: Optional[List[str]] = None  # a, d, e, g, i, ... (3 more)
