# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Glass(StyleBase):
    _name = "glass"

    class Shape(Enum):
        A = "a"
        D = "d"
        E = "e"
        G = "g"
        I = "i"
        N = "n"
        R = "r"
        T = "t"

    def __init__(
            self,
            shape: Shape | str | None = None,
            shape01: Shape | str | None = None,
            shape02: Shape | str | None = None,
    ) -> None:
        super().__init__(
            shape=shape,
            shape01=shape01,
            shape02=shape02,
        )
