# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Glyphs(StyleBase):
    _name = "glyphs"

    class Shape(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"
        VARIANT26 = "variant26"
        VARIANT27 = "variant27"
        VARIANT28 = "variant28"
        VARIANT29 = "variant29"
        VARIANT30 = "variant30"
        VARIANT31 = "variant31"
        VARIANT32 = "variant32"
        VARIANT33 = "variant33"
        VARIANT34 = "variant34"
        VARIANT35 = "variant35"

    class GlyphColor(Enum):
        C76A7FF = "#76a7ff"
        C525FA3 = "#525fa3"
        C8C8C8C = "#8c8c8c"
        C75C675 = "#75c675"
        CFFAA64 = "#ffaa64"
        CFF4D6F = "#ff4d6f"
        CAF61F2 = "#af61f2"

    def __init__(
            self,
            shape: Shape | str | None = None,
            glyphColor: GlyphColor | str | None = None,
    ) -> None:
        super().__init__(
            shape=shape,
            glyphColor=glyphColor,
        )
