# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/glyphs.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Glyphs",)


@dataclass
class Glyphs(StyleBase):
    style_name: ClassVar[str] = "glyphs"

    shape: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (30 more)

    glyphColor: Optional[DColor] = None  # 76a7ff, 525fa3, 8c8c8c, 75c675, ffaa64, ... (2 more)
