# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/icons.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Icons",)


@dataclass
class Icons(StyleBase):
    style_name: ClassVar[str] = "icons"

    icon: Optional[List[str]] = None  # alarm, archive, award, bag, bandaid, ... (141 more)

    iconColor: Optional[DColor] = None  # 000000, ffffff
