# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/identicon.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Identicon",)


@dataclass
class Identicon(StyleBase):
    style_name: ClassVar[str] = "identicon"

    row: Optional[List[str]] = None  # ooxoo, oxoxo, oxxxo, xooox, xoxox, ... (2 more)

    rowColor: Optional[DColor] = None  # e45e4d, de6811, c67c11, b18911, 9b9312, ... (14 more)
