# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Identicon(StyleBase):
    _name = "identicon"

    class Row(Enum):
        OOXOO = "ooxoo"
        OXOXO = "oxoxo"
        OXXXO = "oxxxo"
        XOOOX = "xooox"
        XOXOX = "xoxox"
        XXOXX = "xxoxx"
        XXXXX = "xxxxx"

    class RowColor(Enum):
        CE45E4D = "#e45e4d"
        CDE6811 = "#de6811"
        CC67C11 = "#c67c11"
        CB18911 = "#b18911"
        C9B9312 = "#9b9312"
        C7A9F12 = "#7a9f12"
        C40A843 = "#40a843"
        C15A876 = "#15a876"
        C15A594 = "#15a594"
        C15A2A9 = "#15a2a9"
        C159FBF = "#159fbf"
        C1499DA = "#1499da"
        C448EF4 = "#448ef4"
        C7681F5 = "#7681f5"
        C9975EA = "#9975ea"
        CB46BD6 = "#b46bd6"
        CCA62BB = "#ca62bb"
        CD95C9A = "#d95c9a"
        CE25A75 = "#e25a75"

    def __init__(
        self,
        row: Row | str | None = None,
        row01: Row | str | None = None,
        row02: Row | str | None = None,
        row03: Row | str | None = None,
        row04: Row | str | None = None,
        row05: Row | str | None = None,
        rowColor: RowColor | str | None = None,
    ) -> None:
        super().__init__(
            row=row,
            row01=row01,
            row02=row02,
            row03=row03,
            row04=row04,
            row05=row05,
            rowColor=rowColor,
        )
