# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/initial-face.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("InitialFace",)


@dataclass
class InitialFace(StyleBase):
    style_name: ClassVar[str] = "initial-face"

    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (3 more)
    face: Optional[List[str]] = None  # default
    head: Optional[List[str]] = None  # alt, default
    mouth: Optional[List[str]] = None  # default

    eyesColor: Optional[DColor] = None  # 000000, ffffff
    mouthColor: Optional[DColor] = None  # 000000, ffffff
