# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Initials(StyleBase):
    _name = "initials"

    class Initials(Enum):
        ALT = "alt"
        DEFAULT = "default"

    class Letters(Enum):
        SINGLE = "single"
        DOUBLE = "double"

    class TextColor(Enum):
        CFFFFFF = "#ffffff"
        C000000 = "#000000"

    def __init__(
            self,
            initials: Initials | str | None = None,
            letters: Letters | str | None = None,
            textColor: TextColor | str | None = None,
    ) -> None:
        super().__init__(
            initials=initials,
            letters=letters,
            textColor=textColor,
        )
