# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/initials.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Initials",)


@dataclass
class Initials(StyleBase):
    style_name: ClassVar[str] = "initials"

    initials: Optional[List[str]] = None  # alt, default
    letters: Optional[List[str]] = None  # single, double

    textColor: Optional[DColor] = None  # ffffff, 000000
