# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class InitialFace(StyleBase):
    _name = "initial-face"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"

    class Face(Enum):
        DEFAULT = "default"

    class Head(Enum):
        ALT = "alt"
        DEFAULT = "default"

    class Mouth(Enum):
        DEFAULT = "default"

    class EyesColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    class MouthColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    def __init__(
            self,
            eyes: Eyes | str | None = None,
            face: Face | str | None = None,
            head: Head | str | None = None,
            mouth: Mouth | str | None = None,
            eyesColor: EyesColor | str | None = None,
            mouthColor: MouthColor | str | None = None,
    ) -> None:
        super().__init__(
            eyes=eyes,
            face=face,
            head=head,
            mouth=mouth,
            eyesColor=eyesColor,
            mouthColor=mouthColor,
        )
