# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class LoreleiNeutral(StyleBase):
    _name = "lorelei-neutral"

    class Eyebrows(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"

    class Freckles(Enum):
        VARIANT01 = "variant01"

    class Glasses(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"

    class Mouth(Enum):
        HAPPY01 = "happy01"
        HAPPY02 = "happy02"
        HAPPY03 = "happy03"
        HAPPY04 = "happy04"
        HAPPY05 = "happy05"
        HAPPY06 = "happy06"
        HAPPY07 = "happy07"
        HAPPY08 = "happy08"
        HAPPY09 = "happy09"
        HAPPY10 = "happy10"
        HAPPY11 = "happy11"
        HAPPY12 = "happy12"
        HAPPY13 = "happy13"
        HAPPY14 = "happy14"
        HAPPY15 = "happy15"
        HAPPY16 = "happy16"
        HAPPY17 = "happy17"
        HAPPY18 = "happy18"
        SAD01 = "sad01"
        SAD02 = "sad02"
        SAD03 = "sad03"
        SAD04 = "sad04"
        SAD05 = "sad05"
        SAD06 = "sad06"
        SAD07 = "sad07"
        SAD08 = "sad08"
        SAD09 = "sad09"

    class Nose(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"

    class EyebrowsColor(Enum):
        C000000 = "#000000"

    class EyesColor(Enum):
        C000000 = "#000000"

    class FrecklesColor(Enum):
        C000000 = "#000000"

    class GlassesColor(Enum):
        C000000 = "#000000"

    class MouthColor(Enum):
        C000000 = "#000000"

    class NoseColor(Enum):
        C000000 = "#000000"

    def __init__(
            self,
            eyebrows: Eyebrows | str | None = None,
            eyes: Eyes | str | None = None,
            freckles: Freckles | str | None = None,
            frecklesProbability: int | None = None,
            glasses: Glasses | str | None = None,
            glassesProbability: int | None = None,
            mouth: Mouth | str | None = None,
            nose: Nose | str | None = None,
            eyebrowsColor: EyebrowsColor | str | None = None,
            eyesColor: EyesColor | str | None = None,
            frecklesColor: FrecklesColor | str | None = None,
            glassesColor: GlassesColor | str | None = None,
            mouthColor: MouthColor | str | None = None,
            noseColor: NoseColor | str | None = None,
    ) -> None:
        super().__init__(
            eyebrows=eyebrows,
            eyes=eyes,
            freckles=freckles,
            frecklesProbability=frecklesProbability,
            glasses=glasses,
            glassesProbability=glassesProbability,
            mouth=mouth,
            nose=nose,
            eyebrowsColor=eyebrowsColor,
            eyesColor=eyesColor,
            frecklesColor=frecklesColor,
            glassesColor=glassesColor,
            mouthColor=mouthColor,
            noseColor=noseColor,
        )
