# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/lorelei.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Lorelei",)


@dataclass
class Lorelei(StyleBase):
    style_name: ClassVar[str] = "lorelei"

    beard: Optional[List[str]] = None  # variant01, variant02
    earrings: Optional[List[str]] = None  # variant01, variant02, variant03
    eyebrows: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (8 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (19 more)
    freckles: Optional[List[str]] = None  # variant01
    glasses: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05
    hair: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (43 more)
    hairAccessories: Optional[List[str]] = None  # flowers
    head: Optional[List[str]] = None  # variant01, variant02, variant03, variant04
    mouth: Optional[List[str]] = None  # happy01, happy02, happy03, happy04, happy05, ... (22 more)
    nose: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (1 more)

    earringsColor: Optional[DColor] = None  # 000000
    eyebrowsColor: Optional[DColor] = None  # 000000
    eyesColor: Optional[DColor] = None  # 000000
    frecklesColor: Optional[DColor] = None  # 000000
    glassesColor: Optional[DColor] = None  # 000000
    hairColor: Optional[DColor] = None  # 000000
    hairAccessoriesColor: Optional[DColor] = None  # 000000
    mouthColor: Optional[DColor] = None  # 000000
    noseColor: Optional[DColor] = None  # 000000
    skinColor: Optional[DColor] = None  # ffffff
