# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/micah.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Micah",)


@dataclass
class Micah(StyleBase):
    style_name: ClassVar[str] = "micah"

    clothes: Optional[List[str]] = None  # collared, crew, open
    earrings: Optional[List[str]] = None  # hoop, stud
    ears: Optional[List[str]] = None  # attached, detached
    eyebrows: Optional[List[str]] = None  # down, eyelashesDown, eyelashesUp, up
    eyes: Optional[List[str]] = None  # eyes, eyesShadow, round, smiling, smilingShadow
    facialHair: Optional[List[str]] = None  # beard, scruff
    glasses: Optional[List[str]] = None  # round, square
    hair: Optional[List[str]] = None  # dannyPhantom, dougFunny, fonze, full, mrClean, ... (3 more)
    head: Optional[List[str]] = None  # standard
    mouth: Optional[List[str]] = None  # frown, laughing, nervous, pucker, sad, ... (3 more)
    nose: Optional[List[str]] = None  # curve, pointed, tound

    baseColor: Optional[DColor] = None  # f9c9b6, ac6651, 77311d
    earringColor: Optional[DColor] = None  # f9c9b6, d2eff3, 000000, e0ddff, f4d150, ... (8 more)
    eyeShadowColor: Optional[DColor] = None  # d2eff3, e0ddff, ffeba4, ffedef, ffffff
    eyebrowsColor: Optional[DColor] = None  # 000000
    eyesColor: Optional[DColor] = None  # 000000
    facialHairColor: Optional[DColor] = None  # 000000
    glassesColor: Optional[DColor] = None  # f9c9b6, d2eff3, 000000, e0ddff, f4d150, ... (8 more)
    hairColor: Optional[DColor] = None  # f9c9b6, d2eff3, 000000, e0ddff, f4d150, ... (8 more)
    mouthColor: Optional[DColor] = None  # 000000
    shirtColor: Optional[DColor] = None  # f9c9b6, d2eff3, 000000, e0ddff, f4d150, ... (8 more)
