# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Micah(StyleBase):
    _name = "micah"

    class Clothes(Enum):
        COLLARED = "collared"
        CREW = "crew"
        OPEN = "open"

    class Earrings(Enum):
        HOOP = "hoop"
        STUD = "stud"

    class Ears(Enum):
        ATTACHED = "attached"
        DETACHED = "detached"

    class Eyebrows(Enum):
        DOWN = "down"
        EYELASHES_DOWN = "eyelashesDown"
        EYELASHES_UP = "eyelashesUp"
        UP = "up"

    class Eyes(Enum):
        EYES = "eyes"
        EYES_SHADOW = "eyesShadow"
        ROUND = "round"
        SMILING = "smiling"
        SMILING_SHADOW = "smilingShadow"

    class FacialHair(Enum):
        BEARD = "beard"
        SCRUFF = "scruff"

    class Glasses(Enum):
        ROUND = "round"
        SQUARE = "square"

    class Hair(Enum):
        DANNY_PHANTOM = "dannyPhantom"
        DOUG_FUNNY = "dougFunny"
        FONZE = "fonze"
        FULL = "full"
        MR_CLEAN = "mrClean"
        MR_T = "mrT"
        PIXIE = "pixie"
        TURBAN = "turban"

    class Head(Enum):
        STANDARD = "standard"

    class Mouth(Enum):
        FROWN = "frown"
        LAUGHING = "laughing"
        NERVOUS = "nervous"
        PUCKER = "pucker"
        SAD = "sad"
        SMILE = "smile"
        SMIRK = "smirk"
        SURPRISED = "surprised"

    class Nose(Enum):
        CURVE = "curve"
        POINTED = "pointed"
        TOUND = "tound"

    class BaseColor(Enum):
        CF9C9B6 = "#f9c9b6"
        CAC6651 = "#ac6651"
        C77311D = "#77311d"

    class EarringColor(Enum):
        CF9C9B6 = "#f9c9b6"
        CD2EFF3 = "#d2eff3"
        C000000 = "#000000"
        CE0DDFF = "#e0ddff"
        CF4D150 = "#f4d150"
        CAC6651 = "#ac6651"
        C9287FF = "#9287ff"
        CFFEBA4 = "#ffeba4"
        CFC909F = "#fc909f"
        CFFEDEF = "#ffedef"
        C6BD9E9 = "#6bd9e9"
        C77311D = "#77311d"
        CFFFFFF = "#ffffff"

    class EyeShadowColor(Enum):
        CD2EFF3 = "#d2eff3"
        CE0DDFF = "#e0ddff"
        CFFEBA4 = "#ffeba4"
        CFFEDEF = "#ffedef"
        CFFFFFF = "#ffffff"

    class EyebrowsColor(Enum):
        C000000 = "#000000"

    class EyesColor(Enum):
        C000000 = "#000000"

    class FacialHairColor(Enum):
        C000000 = "#000000"

    class GlassesColor(Enum):
        CF9C9B6 = "#f9c9b6"
        CD2EFF3 = "#d2eff3"
        C000000 = "#000000"
        CE0DDFF = "#e0ddff"
        CF4D150 = "#f4d150"
        CAC6651 = "#ac6651"
        C9287FF = "#9287ff"
        CFFEBA4 = "#ffeba4"
        CFC909F = "#fc909f"
        CFFEDEF = "#ffedef"
        C6BD9E9 = "#6bd9e9"
        C77311D = "#77311d"
        CFFFFFF = "#ffffff"

    class HairColor(Enum):
        CF9C9B6 = "#f9c9b6"
        CD2EFF3 = "#d2eff3"
        C000000 = "#000000"
        CE0DDFF = "#e0ddff"
        CF4D150 = "#f4d150"
        CAC6651 = "#ac6651"
        C9287FF = "#9287ff"
        CFFEBA4 = "#ffeba4"
        CFC909F = "#fc909f"
        CFFEDEF = "#ffedef"
        C6BD9E9 = "#6bd9e9"
        C77311D = "#77311d"
        CFFFFFF = "#ffffff"

    class MouthColor(Enum):
        C000000 = "#000000"

    class ShirtColor(Enum):
        CF9C9B6 = "#f9c9b6"
        CD2EFF3 = "#d2eff3"
        C000000 = "#000000"
        CE0DDFF = "#e0ddff"
        CF4D150 = "#f4d150"
        CAC6651 = "#ac6651"
        C9287FF = "#9287ff"
        CFFEBA4 = "#ffeba4"
        CFC909F = "#fc909f"
        CFFEDEF = "#ffedef"
        C6BD9E9 = "#6bd9e9"
        C77311D = "#77311d"
        CFFFFFF = "#ffffff"

    def __init__(
        self,
        clothes: Clothes | str | None = None,
        earrings: Earrings | str | None = None,
        earringsProbability: int | None = None,
        ears: Ears | str | None = None,
        eyebrows: Eyebrows | str | None = None,
        eyes: Eyes | str | None = None,
        facialHair: FacialHair | str | None = None,
        facialHairProbability: int | None = None,
        glasses: Glasses | str | None = None,
        glassesProbability: int | None = None,
        hair: Hair | str | None = None,
        hairProbability: int | None = None,
        head: Head | str | None = None,
        mouth: Mouth | str | None = None,
        nose: Nose | str | None = None,
        baseColor: BaseColor | str | None = None,
        earringColor: EarringColor | str | None = None,
        eyeShadowColor: EyeShadowColor | str | None = None,
        eyebrowsColor: EyebrowsColor | str | None = None,
        eyesColor: EyesColor | str | None = None,
        facialHairColor: FacialHairColor | str | None = None,
        glassesColor: GlassesColor | str | None = None,
        hairColor: HairColor | str | None = None,
        mouthColor: MouthColor | str | None = None,
        shirtColor: ShirtColor | str | None = None,
    ) -> None:
        super().__init__(
            clothes=clothes,
            earrings=earrings,
            earringsProbability=earringsProbability,
            ears=ears,
            eyebrows=eyebrows,
            eyes=eyes,
            facialHair=facialHair,
            facialHairProbability=facialHairProbability,
            glasses=glasses,
            glassesProbability=glassesProbability,
            hair=hair,
            hairProbability=hairProbability,
            head=head,
            mouth=mouth,
            nose=nose,
            baseColor=baseColor,
            earringColor=earringColor,
            eyeShadowColor=eyeShadowColor,
            eyebrowsColor=eyebrowsColor,
            eyesColor=eyesColor,
            facialHairColor=facialHairColor,
            glassesColor=glassesColor,
            hairColor=hairColor,
            mouthColor=mouthColor,
            shirtColor=shirtColor,
        )
