# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/miniavs.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Miniavs",)


@dataclass
class Miniavs(StyleBase):
    style_name: ClassVar[str] = "miniavs"

    blush: Optional[List[str]] = None  # default
    body: Optional[List[str]] = None  # golf, tShirt
    eyes: Optional[List[str]] = None  # confident, happy, normal
    glasses: Optional[List[str]] = None  # normal
    hair: Optional[List[str]] = None  # balndess, classic01, classic02, curly, elvis, ... (4 more)
    head: Optional[List[str]] = None  # normal, thin, wide
    mouth: Optional[List[str]] = None  # default, missingTooth
    mustache: Optional[List[str]] = None  # freddy, horshoe, pencilThin, pencilThinBeard

    bodyColor: Optional[DColor] = None  # 3633e0, e05a33, ff4dd8
    hairColor: Optional[DColor] = None  # 1b0b47, 47280b, ad3a20
    skinColor: Optional[DColor] = None  # 836055, f5d0c5, ffcb7e
