# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Miniavs(StyleBase):
    _name = "miniavs"

    class Blush(Enum):
        DEFAULT = "default"

    class Body(Enum):
        GOLF = "golf"
        T_SHIRT = "tShirt"

    class Eyes(Enum):
        CONFIDENT = "confident"
        HAPPY = "happy"
        NORMAL = "normal"

    class Glasses(Enum):
        NORMAL = "normal"

    class Hair(Enum):
        BALNDESS = "balndess"
        CLASSIC01 = "classic01"
        CLASSIC02 = "classic02"
        CURLY = "curly"
        ELVIS = "elvis"
        LONG = "long"
        PONY_TAIL = "ponyTail"
        SLAUGHTER = "slaughter"
        STYLISH = "stylish"

    class Head(Enum):
        NORMAL = "normal"
        THIN = "thin"
        WIDE = "wide"

    class Mouth(Enum):
        DEFAULT = "default"
        MISSING_TOOTH = "missingTooth"

    class Mustache(Enum):
        FREDDY = "freddy"
        HORSHOE = "horshoe"
        PENCIL_THIN = "pencilThin"
        PENCIL_THIN_BEARD = "pencilThinBeard"

    class BodyColor(Enum):
        C3633E0 = "#3633e0"
        CE05A33 = "#e05a33"
        CFF4DD8 = "#ff4dd8"

    class HairColor(Enum):
        C1B0B47 = "#1b0b47"
        C47280B = "#47280b"
        CAD3A20 = "#ad3a20"

    class SkinColor(Enum):
        C836055 = "#836055"
        CF5D0C5 = "#f5d0c5"
        CFFCB7E = "#ffcb7e"

    def __init__(
            self,
            blush: Blush | str | None = None,
            blushProbability: int | None = None,
            body: Body | str | None = None,
            eyes: Eyes | str | None = None,
            glasses: Glasses | str | None = None,
            glassesProbability: int | None = None,
            hair: Hair | str | None = None,
            head: Head | str | None = None,
            mouth: Mouth | str | None = None,
            mustache: Mustache | str | None = None,
            mustacheProbability: int | None = None,
            bodyColor: BodyColor | str | None = None,
            hairColor: HairColor | str | None = None,
            skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            blush=blush,
            blushProbability=blushProbability,
            body=body,
            eyes=eyes,
            glasses=glasses,
            glassesProbability=glassesProbability,
            hair=hair,
            head=head,
            mouth=mouth,
            mustache=mustache,
            mustacheProbability=mustacheProbability,
            bodyColor=bodyColor,
            hairColor=hairColor,
            skinColor=skinColor,
        )
