# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/notionists.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("Notionists",)


@dataclass
class Notionists(StyleBase):
    style_name: ClassVar[str] = "notionists"

    beard: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (7 more)
    clothes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (20 more)
    clothesGraphic: Optional[List[str]] = None  # electric, galaxy, saturn
    eyebrows: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (8 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05
    gesture: Optional[List[str]] = None  # hand, handPhone, ok, okLongArm, point, ... (5 more)
    glasses: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (6 more)
    hair: Optional[List[str]] = None  # hat, variant01, variant02, variant03, variant04, ... (59 more)
    head: Optional[List[str]] = None  # variant01
    mouth: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (25 more)
    nose: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (15 more)
