# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Notionists(StyleBase):
    _name = "notionists"

    class Beard(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"

    class Clothes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"

    class ClothesGraphic(Enum):
        ELECTRIC = "electric"
        GALAXY = "galaxy"
        SATURN = "saturn"

    class Eyebrows(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"

    class Gesture(Enum):
        HAND = "hand"
        HAND_PHONE = "handPhone"
        OK = "ok"
        OK_LONG_ARM = "okLongArm"
        POINT = "point"
        POINT_LONG_ARM = "pointLongArm"
        WAVE_LONG_ARM = "waveLongArm"
        WAVE_LONG_ARMS = "waveLongArms"
        WAVE_OK_LONG_ARMS = "waveOkLongArms"
        WAVE_POINT_LONG_ARMS = "wavePointLongArms"

    class Glasses(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"

    class Hair(Enum):
        HAT = "hat"
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"
        VARIANT26 = "variant26"
        VARIANT27 = "variant27"
        VARIANT28 = "variant28"
        VARIANT29 = "variant29"
        VARIANT30 = "variant30"
        VARIANT31 = "variant31"
        VARIANT32 = "variant32"
        VARIANT33 = "variant33"
        VARIANT34 = "variant34"
        VARIANT35 = "variant35"
        VARIANT36 = "variant36"
        VARIANT37 = "variant37"
        VARIANT38 = "variant38"
        VARIANT39 = "variant39"
        VARIANT40 = "variant40"
        VARIANT41 = "variant41"
        VARIANT42 = "variant42"
        VARIANT43 = "variant43"
        VARIANT44 = "variant44"
        VARIANT45 = "variant45"
        VARIANT46 = "variant46"
        VARIANT47 = "variant47"
        VARIANT48 = "variant48"
        VARIANT49 = "variant49"
        VARIANT50 = "variant50"
        VARIANT51 = "variant51"
        VARIANT52 = "variant52"
        VARIANT53 = "variant53"
        VARIANT54 = "variant54"
        VARIANT55 = "variant55"
        VARIANT56 = "variant56"
        VARIANT57 = "variant57"
        VARIANT58 = "variant58"
        VARIANT59 = "variant59"
        VARIANT60 = "variant60"
        VARIANT61 = "variant61"
        VARIANT62 = "variant62"
        VARIANT63 = "variant63"

    class Head(Enum):
        VARIANT01 = "variant01"

    class Mouth(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"
        VARIANT24 = "variant24"
        VARIANT25 = "variant25"
        VARIANT26 = "variant26"
        VARIANT27 = "variant27"
        VARIANT28 = "variant28"
        VARIANT29 = "variant29"
        VARIANT30 = "variant30"

    class Nose(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"

    def __init__(
            self,
            beard: Beard | str | None = None,
            beardProbability: int | None = None,
            clothes: Clothes | str | None = None,
            clothesGraphic: ClothesGraphic | str | None = None,
            clothesGraphicProbability: int | None = None,
            eyebrows: Eyebrows | str | None = None,
            eyes: Eyes | str | None = None,
            gesture: Gesture | str | None = None,
            gestureProbability: int | None = None,
            glasses: Glasses | str | None = None,
            glassesProbability: int | None = None,
            hair: Hair | str | None = None,
            head: Head | str | None = None,
            mouth: Mouth | str | None = None,
            nose: Nose | str | None = None,
    ) -> None:
        super().__init__(
            beard=beard,
            beardProbability=beardProbability,
            clothes=clothes,
            clothesGraphic=clothesGraphic,
            clothesGraphicProbability=clothesGraphicProbability,
            eyebrows=eyebrows,
            eyes=eyes,
            gesture=gesture,
            gestureProbability=gestureProbability,
            glasses=glasses,
            glassesProbability=glassesProbability,
            hair=hair,
            head=head,
            mouth=mouth,
            nose=nose,
        )
