# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/notionists-neutral.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ._base import StyleBase

__all__ = ("NotionistsNeutral",)


@dataclass
class NotionistsNeutral(StyleBase):
    style_name: ClassVar[str] = "notionists-neutral"

    eyebrows: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (8 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05
    glasses: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (6 more)
    mouth: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (25 more)
    nose: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (15 more)
