# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class OpenPeeps(StyleBase):
    _name = "open-peeps"

    class Accessories(Enum):
        EYEPATCH = "eyepatch"
        GLASSES = "glasses"
        GLASSES2 = "glasses2"
        GLASSES3 = "glasses3"
        GLASSES4 = "glasses4"
        GLASSES5 = "glasses5"
        SUNGLASSES = "sunglasses"
        SUNGLASSES2 = "sunglasses2"

    class Expression(Enum):
        ANGRY_WITH_FANG = "angryWithFang"
        AWE = "awe"
        BLANK = "blank"
        CALM = "calm"
        CHEEKY = "cheeky"
        CONCERNED = "concerned"
        CONCERNED_FEAR = "concernedFear"
        CONTEMPT = "contempt"
        CUTE = "cute"
        CYCLOPS = "cyclops"
        DRIVEN = "driven"
        EATING_HAPPY = "eatingHappy"
        EXPLAINING = "explaining"
        EYES_CLOSED = "eyesClosed"
        FEAR = "fear"
        HECTIC = "hectic"
        LOVING_GRIN1 = "lovingGrin1"
        LOVING_GRIN2 = "lovingGrin2"
        MONSTER = "monster"
        OLD = "old"
        RAGE = "rage"
        SERIOUS = "serious"
        SMILE = "smile"
        SMILE_BIG = "smileBig"
        SMILE_LOL = "smileLOL"
        SMILE_TEETH_GAP = "smileTeethGap"
        SOLEMN = "solemn"
        SUSPICIOUS = "suspicious"
        TIRED = "tired"
        VERY_ANGRY = "veryAngry"

    class FacialHair(Enum):
        CHIN = "chin"
        FULL = "full"
        FULL2 = "full2"
        FULL3 = "full3"
        FULL4 = "full4"
        GOATEE1 = "goatee1"
        GOATEE2 = "goatee2"
        MOUSTACHE1 = "moustache1"
        MOUSTACHE2 = "moustache2"
        MOUSTACHE3 = "moustache3"
        MOUSTACHE4 = "moustache4"
        MOUSTACHE5 = "moustache5"
        MOUSTACHE6 = "moustache6"
        MOUSTACHE7 = "moustache7"
        MOUSTACHE8 = "moustache8"
        MOUSTACHE9 = "moustache9"

    class Head(Enum):
        AFRO = "afro"
        BANGS = "bangs"
        BANGS2 = "bangs2"
        BANTU_KNOTS = "bantuKnots"
        BEAR = "bear"
        BUN = "bun"
        BUN2 = "bun2"
        BUNS = "buns"
        CORNROWS = "cornrows"
        CORNROWS2 = "cornrows2"
        DREADS1 = "dreads1"
        DREADS2 = "dreads2"
        FLAT_TOP = "flatTop"
        FLAT_TOP_LONG = "flatTopLong"
        GRAY_BUN = "grayBun"
        GRAY_MEDIUM = "grayMedium"
        GRAY_SHORT = "grayShort"
        HAT_BEANIE = "hatBeanie"
        HAT_HIP = "hatHip"
        HIJAB = "hijab"
        LONG = "long"
        LONG_AFRO = "longAfro"
        LONG_BANGS = "longBangs"
        LONG_CURLY = "longCurly"
        MEDIUM1 = "medium1"
        MEDIUM2 = "medium2"
        MEDIUM3 = "medium3"
        MEDIUM_BANGS = "mediumBangs"
        MEDIUM_BANGS2 = "mediumBangs2"
        MEDIUM_BANGS3 = "mediumBangs3"
        MEDIUM_STRAIGHT = "mediumStraight"
        MOHAWK = "mohawk"
        MOHAWK2 = "mohawk2"
        NO_HAIR1 = "noHair1"
        NO_HAIR2 = "noHair2"
        NO_HAIR3 = "noHair3"
        POMP = "pomp"
        SHAVED1 = "shaved1"
        SHAVED2 = "shaved2"
        SHAVED3 = "shaved3"
        SHORT1 = "short1"
        SHORT2 = "short2"
        SHORT3 = "short3"
        SHORT4 = "short4"
        SHORT5 = "short5"
        TURBAN = "turban"
        TWISTS = "twists"
        TWISTS2 = "twists2"

    class Mask(Enum):
        MEDICAL_MASK = "medicalMask"
        RESPIRATOR = "respirator"

    class ClothingColor(Enum):
        C8FA7DF = "#8fa7df"
        C78E185 = "#78e185"
        CFFCF77 = "#ffcf77"
        CE279C7 = "#e279c7"
        CE78276 = "#e78276"
        C9DDADB = "#9ddadb"
        CFDEA6B = "#fdea6b"

    class HeadContrastColor(Enum):
        C2C1B18 = "#2c1b18"
        CE8E1E1 = "#e8e1e1"
        CECDCBF = "#ecdcbf"
        CD6B370 = "#d6b370"
        CF59797 = "#f59797"
        CB58143 = "#b58143"
        CA55728 = "#a55728"
        C724133 = "#724133"
        C4A312C = "#4a312c"
        CC93305 = "#c93305"

    class SkinColor(Enum):
        CFFDBB4 = "#ffdbb4"
        CEDB98A = "#edb98a"
        CD08B5B = "#d08b5b"
        CAE5D29 = "#ae5d29"
        C694D3D = "#694d3d"

    def __init__(
            self,
            accessories: Accessories | str | None = None,
            accessoriesProbability: int | None = None,
            expression: Expression | str | None = None,
            facialHair: FacialHair | str | None = None,
            facialHairProbability: int | None = None,
            head: Head | str | None = None,
            mask: Mask | str | None = None,
            maskProbability: int | None = None,
            clothingColor: ClothingColor | str | None = None,
            headContrastColor: HeadContrastColor | str | None = None,
            skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            accessories=accessories,
            accessoriesProbability=accessoriesProbability,
            expression=expression,
            facialHair=facialHair,
            facialHairProbability=facialHairProbability,
            head=head,
            mask=mask,
            maskProbability=maskProbability,
            clothingColor=clothingColor,
            headContrastColor=headContrastColor,
            skinColor=skinColor,
        )
