# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/open-peeps.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("OpenPeeps",)


@dataclass
class OpenPeeps(StyleBase):
    style_name: ClassVar[str] = "open-peeps"

    accessories: Optional[List[str]] = None  # eyepatch, glasses, glasses2, glasses3, glasses4, ... (3 more)
    expression: Optional[List[str]] = None  # angryWithFang, awe, blank, calm, cheeky, ... (25 more)
    facialHair: Optional[List[str]] = None  # chin, full, full2, full3, full4, ... (11 more)
    head: Optional[List[str]] = None  # afro, bangs, bangs2, bantuKnots, bear, ... (43 more)
    mask: Optional[List[str]] = None  # medicalMask, respirator

    clothingColor: Optional[DColor] = None  # 8fa7df, 78e185, ffcf77, e279c7, e78276, ... (2 more)
    headContrastColor: Optional[DColor] = None  # 2c1b18, e8e1e1, ecdcbf, d6b370, f59797, ... (5 more)
    skinColor: Optional[DColor] = None  # ffdbb4, edb98a, d08b5b, ae5d29, 694d3d
