# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Personas(StyleBase):
    _name = "personas"

    class Clothes(Enum):
        CHECKERED = "checkered"
        ROUNDED = "rounded"
        SMALL = "small"
        SQUARED = "squared"

    class Eyes(Enum):
        GLASSES = "glasses"
        HAPPY = "happy"
        OPEN = "open"
        SLEEP = "sleep"
        SUNGLASSES = "sunglasses"
        WINK = "wink"

    class FacialHair(Enum):
        BEARD_MUSTACHE = "beardMustache"
        GOATEE = "goatee"
        PYRAMID = "pyramid"
        SHADOW = "shadow"
        SOUL_PATCH = "soulPatch"
        WALRUS = "walrus"

    class Hair(Enum):
        BALD = "bald"
        BALDING = "balding"
        BEANIE = "beanie"
        BOB_BANGS = "bobBangs"
        BOB_CUT = "bobCut"
        BUN_UNDERCUT = "bunUndercut"
        BUZZCUT = "buzzcut"
        CAP = "cap"
        CURLY = "curly"
        CURLY_BUN = "curlyBun"
        CURLY_HIGH_TOP = "curlyHighTop"
        EXTRA_LONG = "extraLong"
        FADE = "fade"
        LONG = "long"
        MOHAWK = "mohawk"
        PIGTAILS = "pigtails"
        SHORT_COMBOVER = "shortCombover"
        SHORT_COMBOVER_CHOPS = "shortComboverChops"
        SIDE_SHAVE = "sideShave"
        STRAIGHT_BUN = "straightBun"

    class Mouth(Enum):
        BIG_SMILE = "bigSmile"
        FROWN = "frown"
        LIPS = "lips"
        PACIFIER = "pacifier"
        SMILE = "smile"
        SMIRK = "smirk"
        SURPRISE = "surprise"

    class Nose(Enum):
        MEDIUM_ROUND = "mediumRound"
        SMALL_ROUND = "smallRound"
        WRINKLES = "wrinkles"

    class ClothingColor(Enum):
        C456DFF = "#456dff"
        C6DBB58 = "#6dbb58"
        CF55D81 = "#f55d81"
        C7555CA = "#7555ca"
        CE24553 = "#e24553"
        C54D7C7 = "#54d7c7"
        CF3B63A = "#f3b63a"

    class FacialHairColor(Enum):
        C362C47 = "#362c47"
        CF29C65 = "#f29c65"
        C6C4545 = "#6c4545"
        CF27D65 = "#f27d65"
        CDEE1F5 = "#dee1f5"
        CE16381 = "#e16381"
        CE15C66 = "#e15c66"

    class HairColor(Enum):
        C362C47 = "#362c47"
        CF29C65 = "#f29c65"
        C6C4545 = "#6c4545"
        CF27D65 = "#f27d65"
        CDEE1F5 = "#dee1f5"
        CE16381 = "#e16381"
        CE15C66 = "#e15c66"

    class SkinColor(Enum):
        CEEB4A4 = "#eeb4a4"
        CE7A391 = "#e7a391"
        CE5A07E = "#e5a07e"
        CD78774 = "#d78774"
        CB16A5B = "#b16a5b"
        C92594B = "#92594b"
        C623D36 = "#623d36"

    def __init__(
            self,
            clothes: Clothes | str | None = None,
            eyes: Eyes | str | None = None,
            facialHair: FacialHair | str | None = None,
            facialHairProbability: int | None = None,
            hair: Hair | str | None = None,
            mouth: Mouth | str | None = None,
            nose: Nose | str | None = None,
            clothingColor: ClothingColor | str | None = None,
            facialHairColor: FacialHairColor | str | None = None,
            hairColor: HairColor | str | None = None,
            skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            clothes=clothes,
            eyes=eyes,
            facialHair=facialHair,
            facialHairProbability=facialHairProbability,
            hair=hair,
            mouth=mouth,
            nose=nose,
            clothingColor=clothingColor,
            facialHairColor=facialHairColor,
            hairColor=hairColor,
            skinColor=skinColor,
        )
