# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/personas.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Personas",)


@dataclass
class Personas(StyleBase):
    style_name: ClassVar[str] = "personas"

    clothes: Optional[List[str]] = None  # checkered, rounded, small, squared
    eyes: Optional[List[str]] = None  # glasses, happy, open, sleep, sunglasses, ... (1 more)
    facialHair: Optional[List[str]] = None  # beardMustache, goatee, pyramid, shadow, soulPatch, ... (1 more)
    hair: Optional[List[str]] = None  # bald, balding, beanie, bobBangs, bobCut, ... (15 more)
    mouth: Optional[List[str]] = None  # bigSmile, frown, lips, pacifier, smile, ... (2 more)
    nose: Optional[List[str]] = None  # mediumRound, smallRound, wrinkles

    clothingColor: Optional[DColor] = None  # 456dff, 6dbb58, f55d81, 7555ca, e24553, ... (2 more)
    facialHairColor: Optional[DColor] = None  # 362c47, f29c65, 6c4545, f27d65, dee1f5, ... (2 more)
    hairColor: Optional[DColor] = None  # 362c47, f29c65, 6c4545, f27d65, dee1f5, ... (2 more)
    skinColor: Optional[DColor] = None  # eeb4a4, e7a391, e5a07e, d78774, b16a5b, ... (2 more)
