# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/pixel-art.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("PixelArt",)


@dataclass
class PixelArt(StyleBase):
    style_name: ClassVar[str] = "pixel-art"

    accessories: Optional[List[str]] = None  # variant01, variant02, variant03, variant04
    beard: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (3 more)
    clothes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (18 more)
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (7 more)
    glasses: Optional[List[str]] = None  # dark01, dark02, dark03, dark04, dark05, ... (9 more)
    hair: Optional[List[str]] = None  # long01, long02, long03, long04, long05, ... (40 more)
    hat: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (5 more)
    mouth: Optional[List[str]] = None  # happy01, happy02, happy03, happy04, happy05, ... (18 more)

    accessoriesColor: Optional[DColor] = None  # daa520, ffd700, fafad2, d3d3d3, a9a9a9
    clothingColor: Optional[DColor] = None  # 5bc0de, 428bca, 03396c, 88d8b0, 44c585, ... (7 more)
    eyesColor: Optional[DColor] = None  # 76778b, 697b94, 647b90, 5b7c8b, 588387, ... (1 more)
    glassesColor: Optional[DColor] = None  # 4b4b4b, 323232, 191919, 43677d, 5f705c, ... (1 more)
    hairColor: Optional[DColor] = None  # cab188, 603a14, 83623b, a78961, 611c17, ... (6 more)
    hatColor: Optional[DColor] = None  # 2e1e05, 2663a3, 989789, 3d8a6b, cc6192, ... (2 more)
    mouthColor: Optional[DColor] = None  # d29985, c98276, e35d6a, de0f0d
    skinColor: Optional[DColor] = None  # ffdbac, f5cfa0, eac393, e0b687, cb9e6e, ... (3 more)
