# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/pixel-art-neutral.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("PixelArtNeutral",)


@dataclass
class PixelArtNeutral(StyleBase):
    style_name: ClassVar[str] = "pixel-art-neutral"

    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (7 more)
    glasses: Optional[List[str]] = None  # dark01, dark02, dark03, dark04, dark05, ... (9 more)
    mouth: Optional[List[str]] = None  # happy01, happy02, happy03, happy04, happy05, ... (18 more)

    eyesColor: Optional[DColor] = None  # 76778b, 697b94, 647b90, 5b7c8b, 588387, ... (1 more)
    glassesColor: Optional[DColor] = None  # 4b4b4b, 323232, 191919, 43677d, 5f705c, ... (1 more)
    mouthColor: Optional[DColor] = None  # d29985, c98276, e35d6a, de0f0d
