# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class PixelArtNeutral(StyleBase):
    _name = "pixel-art-neutral"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"

    class Glasses(Enum):
        DARK01 = "dark01"
        DARK02 = "dark02"
        DARK03 = "dark03"
        DARK04 = "dark04"
        DARK05 = "dark05"
        DARK06 = "dark06"
        DARK07 = "dark07"
        LIGHT01 = "light01"
        LIGHT02 = "light02"
        LIGHT03 = "light03"
        LIGHT04 = "light04"
        LIGHT05 = "light05"
        LIGHT06 = "light06"
        LIGHT07 = "light07"

    class Mouth(Enum):
        HAPPY01 = "happy01"
        HAPPY02 = "happy02"
        HAPPY03 = "happy03"
        HAPPY04 = "happy04"
        HAPPY05 = "happy05"
        HAPPY06 = "happy06"
        HAPPY07 = "happy07"
        HAPPY08 = "happy08"
        HAPPY09 = "happy09"
        HAPPY10 = "happy10"
        HAPPY11 = "happy11"
        HAPPY12 = "happy12"
        HAPPY13 = "happy13"
        SAD01 = "sad01"
        SAD02 = "sad02"
        SAD03 = "sad03"
        SAD04 = "sad04"
        SAD05 = "sad05"
        SAD06 = "sad06"
        SAD07 = "sad07"
        SAD08 = "sad08"
        SAD09 = "sad09"
        SAD10 = "sad10"

    class EyesColor(Enum):
        C76778B = "#76778b"
        C697B94 = "#697b94"
        C647B90 = "#647b90"
        C5B7C8B = "#5b7c8b"
        C588387 = "#588387"
        C876658 = "#876658"

    class GlassesColor(Enum):
        C4B4B4B = "#4b4b4b"
        C323232 = "#323232"
        C191919 = "#191919"
        C43677D = "#43677d"
        C5F705C = "#5f705c"
        CA04B5D = "#a04b5d"

    class MouthColor(Enum):
        CD29985 = "#d29985"
        CC98276 = "#c98276"
        CE35D6A = "#e35d6a"
        CDE0F0D = "#de0f0d"

    def __init__(
        self,
        eyes: Eyes | str | None = None,
        glasses: Glasses | str | None = None,
        glassesProbability: int | None = None,
        mouth: Mouth | str | None = None,
        eyesColor: EyesColor | str | None = None,
        glassesColor: GlassesColor | str | None = None,
        mouthColor: MouthColor | str | None = None,
    ) -> None:
        super().__init__(
            eyes=eyes,
            glasses=glasses,
            glassesProbability=glassesProbability,
            mouth=mouth,
            eyesColor=eyesColor,
            glassesColor=glassesColor,
            mouthColor=mouthColor,
        )
