# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class PixelArt(StyleBase):
    _name = "pixel-art"

    class Accessories(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"

    class Beard(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"

    class Clothes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"
        VARIANT13 = "variant13"
        VARIANT14 = "variant14"
        VARIANT15 = "variant15"
        VARIANT16 = "variant16"
        VARIANT17 = "variant17"
        VARIANT18 = "variant18"
        VARIANT19 = "variant19"
        VARIANT20 = "variant20"
        VARIANT21 = "variant21"
        VARIANT22 = "variant22"
        VARIANT23 = "variant23"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"
        VARIANT11 = "variant11"
        VARIANT12 = "variant12"

    class Glasses(Enum):
        DARK01 = "dark01"
        DARK02 = "dark02"
        DARK03 = "dark03"
        DARK04 = "dark04"
        DARK05 = "dark05"
        DARK06 = "dark06"
        DARK07 = "dark07"
        LIGHT01 = "light01"
        LIGHT02 = "light02"
        LIGHT03 = "light03"
        LIGHT04 = "light04"
        LIGHT05 = "light05"
        LIGHT06 = "light06"
        LIGHT07 = "light07"

    class Hair(Enum):
        LONG01 = "long01"
        LONG02 = "long02"
        LONG03 = "long03"
        LONG04 = "long04"
        LONG05 = "long05"
        LONG06 = "long06"
        LONG07 = "long07"
        LONG08 = "long08"
        LONG09 = "long09"
        LONG10 = "long10"
        LONG11 = "long11"
        LONG12 = "long12"
        LONG13 = "long13"
        LONG14 = "long14"
        LONG15 = "long15"
        LONG16 = "long16"
        LONG17 = "long17"
        LONG18 = "long18"
        LONG19 = "long19"
        LONG20 = "long20"
        LONG21 = "long21"
        SHORT01 = "short01"
        SHORT02 = "short02"
        SHORT03 = "short03"
        SHORT04 = "short04"
        SHORT05 = "short05"
        SHORT06 = "short06"
        SHORT07 = "short07"
        SHORT08 = "short08"
        SHORT09 = "short09"
        SHORT10 = "short10"
        SHORT11 = "short11"
        SHORT12 = "short12"
        SHORT13 = "short13"
        SHORT14 = "short14"
        SHORT15 = "short15"
        SHORT16 = "short16"
        SHORT17 = "short17"
        SHORT18 = "short18"
        SHORT19 = "short19"
        SHORT20 = "short20"
        SHORT21 = "short21"
        SHORT22 = "short22"
        SHORT23 = "short23"
        SHORT24 = "short24"

    class Hat(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"
        VARIANT09 = "variant09"
        VARIANT10 = "variant10"

    class Mouth(Enum):
        HAPPY01 = "happy01"
        HAPPY02 = "happy02"
        HAPPY03 = "happy03"
        HAPPY04 = "happy04"
        HAPPY05 = "happy05"
        HAPPY06 = "happy06"
        HAPPY07 = "happy07"
        HAPPY08 = "happy08"
        HAPPY09 = "happy09"
        HAPPY10 = "happy10"
        HAPPY11 = "happy11"
        HAPPY12 = "happy12"
        HAPPY13 = "happy13"
        SAD01 = "sad01"
        SAD02 = "sad02"
        SAD03 = "sad03"
        SAD04 = "sad04"
        SAD05 = "sad05"
        SAD06 = "sad06"
        SAD07 = "sad07"
        SAD08 = "sad08"
        SAD09 = "sad09"
        SAD10 = "sad10"

    class AccessoriesColor(Enum):
        CDAA520 = "#daa520"
        CFFD700 = "#ffd700"
        CFAFAD2 = "#fafad2"
        CD3D3D3 = "#d3d3d3"
        CA9A9A9 = "#a9a9a9"

    class ClothingColor(Enum):
        C5BC0DE = "#5bc0de"
        C428BCA = "#428bca"
        C03396C = "#03396c"
        C88D8B0 = "#88d8b0"
        C44C585 = "#44c585"
        C00B159 = "#00b159"
        CFF6F69 = "#ff6f69"
        CD11141 = "#d11141"
        CAE0001 = "#ae0001"
        CFFEEAD = "#ffeead"
        CFFD969 = "#ffd969"
        CFFC425 = "#ffc425"

    class EyesColor(Enum):
        C76778B = "#76778b"
        C697B94 = "#697b94"
        C647B90 = "#647b90"
        C5B7C8B = "#5b7c8b"
        C588387 = "#588387"
        C876658 = "#876658"

    class GlassesColor(Enum):
        C4B4B4B = "#4b4b4b"
        C323232 = "#323232"
        C191919 = "#191919"
        C43677D = "#43677d"
        C5F705C = "#5f705c"
        CA04B5D = "#a04b5d"

    class HairColor(Enum):
        CCAB188 = "#cab188"
        C603A14 = "#603a14"
        C83623B = "#83623b"
        CA78961 = "#a78961"
        C611C17 = "#611c17"
        C603015 = "#603015"
        C612616 = "#612616"
        C28150A = "#28150a"
        C009BBD = "#009bbd"
        CBD1700 = "#bd1700"
        C91CB15 = "#91cb15"

    class HatColor(Enum):
        C2E1E05 = "#2e1e05"
        C2663A3 = "#2663a3"
        C989789 = "#989789"
        C3D8A6B = "#3d8a6b"
        CCC6192 = "#cc6192"
        C614F8A = "#614f8a"
        CA62116 = "#a62116"

    class MouthColor(Enum):
        CD29985 = "#d29985"
        CC98276 = "#c98276"
        CE35D6A = "#e35d6a"
        CDE0F0D = "#de0f0d"

    class SkinColor(Enum):
        CFFDBAC = "#ffdbac"
        CF5CFA0 = "#f5cfa0"
        CEAC393 = "#eac393"
        CE0B687 = "#e0b687"
        CCB9E6E = "#cb9e6e"
        CB68655 = "#b68655"
        CA26D3D = "#a26d3d"
        C8D5524 = "#8d5524"

    def __init__(
        self,
        accessories: Accessories | str | None = None,
        accessoriesProbability: int | None = None,
        beard: Beard | str | None = None,
        beardProbability: int | None = None,
        clothes: Clothes | str | None = None,
        eyes: Eyes | str | None = None,
        glasses: Glasses | str | None = None,
        glassesProbability: int | None = None,
        hair: Hair | str | None = None,
        hat: Hat | str | None = None,
        hatProbability: int | None = None,
        mouth: Mouth | str | None = None,
        accessoriesColor: AccessoriesColor | str | None = None,
        clothingColor: ClothingColor | str | None = None,
        eyesColor: EyesColor | str | None = None,
        glassesColor: GlassesColor | str | None = None,
        hairColor: HairColor | str | None = None,
        hatColor: HatColor | str | None = None,
        mouthColor: MouthColor | str | None = None,
        skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            accessories=accessories,
            accessoriesProbability=accessoriesProbability,
            beard=beard,
            beardProbability=beardProbability,
            clothes=clothes,
            eyes=eyes,
            glasses=glasses,
            glassesProbability=glassesProbability,
            hair=hair,
            hat=hat,
            hatProbability=hatProbability,
            mouth=mouth,
            accessoriesColor=accessoriesColor,
            clothingColor=clothingColor,
            eyesColor=eyesColor,
            glassesColor=glassesColor,
            hairColor=hairColor,
            hatColor=hatColor,
            mouthColor=mouthColor,
            skinColor=skinColor,
        )
