# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Rings(StyleBase):
    _name = "rings"

    class Ring(Enum):
        CONTAINER = "container"

    class Ring01(Enum):
        EIGHTH = "eighth"
        FULL = "full"
        HALF = "half"
        QUARTER = "quarter"

    class Ring02(Enum):
        EIGHTH = "eighth"
        FULL = "full"
        HALF = "half"
        QUARTER = "quarter"

    class Ring03(Enum):
        EIGHTH = "eighth"
        FULL = "full"
        HALF = "half"
        QUARTER = "quarter"

    class Ring04(Enum):
        EIGHTH = "eighth"
        FULL = "full"
        HALF = "half"
        QUARTER = "quarter"

    class Ring05(Enum):
        EIGHTH = "eighth"
        FULL = "full"
        HALF = "half"
        QUARTER = "quarter"

    class RingColor(Enum):
        CF49383 = "#f49383"
        CED9B66 = "#ed9b66"
        CDEA552 = "#dea552"
        CC6B14F = "#c6b14f"
        CA7BC61 = "#a7bc61"
        C83C57D = "#83c57d"
        C5BC99E = "#5bc99e"
        C37C9BE = "#37c9be"
        C34C5DB = "#34c5db"
        C55BEF1 = "#55bef1"
        C7BB4FC = "#7bb4fc"
        C9FA9FD = "#9fa9fd"
        CBD9FF2 = "#bd9ff2"
        CD597DE = "#d597de"
        CE791C3 = "#e791c3"
        CF290A3 = "#f290a3"

    def __init__(
            self,
            ring: Ring | str | None = None,
            ring01: Ring01 | str | None = None,
            ring02: Ring02 | str | None = None,
            ring03: Ring03 | str | None = None,
            ring04: Ring04 | str | None = None,
            ring05: Ring05 | str | None = None,
            ringColor: RingColor | str | None = None,
    ) -> None:
        super().__init__(
            ring=ring,
            ring01=ring01,
            ring02=ring02,
            ring03=ring03,
            ring04=ring04,
            ring05=ring05,
            ringColor=ringColor,
        )
