# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/rings.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Rings",)


@dataclass
class Rings(StyleBase):
    style_name: ClassVar[str] = "rings"

    ring: Optional[List[str]] = None  # container
    ring01: Optional[List[str]] = None  # eighth, full, half, quarter
    ring02: Optional[List[str]] = None  # eighth, full, half, quarter
    ring03: Optional[List[str]] = None  # eighth, full, half, quarter
    ring04: Optional[List[str]] = None  # eighth, full, half, quarter
    ring05: Optional[List[str]] = None  # eighth, full, half, quarter

    ringColor: Optional[DColor] = None  # f49383, ed9b66, dea552, c6b14f, a7bc61, ... (11 more)
