# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Shapes(StyleBase):
    _name = "shapes"

    class Shape01(Enum):
        ELLIPSE = "ellipse"
        ELLIPSE_FILLED = "ellipseFilled"
        LINE = "line"
        POLYGON = "polygon"
        POLYGON_FILLED = "polygonFilled"
        RECTANGLE = "rectangle"
        RECTANGLE_FILLED = "rectangleFilled"

    class Shape02(Enum):
        ELLIPSE = "ellipse"
        ELLIPSE_FILLED = "ellipseFilled"
        LINE = "line"
        POLYGON = "polygon"
        POLYGON_FILLED = "polygonFilled"
        RECTANGLE = "rectangle"
        RECTANGLE_FILLED = "rectangleFilled"

    class Shape03(Enum):
        ELLIPSE = "ellipse"
        ELLIPSE_FILLED = "ellipseFilled"
        LINE = "line"
        POLYGON = "polygon"
        POLYGON_FILLED = "polygonFilled"
        RECTANGLE = "rectangle"
        RECTANGLE_FILLED = "rectangleFilled"

    class Shape1Color(Enum):
        C0A5B83 = "#0a5b83"
        C1C799F = "#1c799f"
        C69D2E7 = "#69d2e7"
        CF1F4DC = "#f1f4dc"
        CF88C49 = "#f88c49"

    class Shape2Color(Enum):
        C0A5B83 = "#0a5b83"
        C1C799F = "#1c799f"
        C69D2E7 = "#69d2e7"
        CF1F4DC = "#f1f4dc"
        CF88C49 = "#f88c49"

    class Shape3Color(Enum):
        C0A5B83 = "#0a5b83"
        C1C799F = "#1c799f"
        C69D2E7 = "#69d2e7"
        CF1F4DC = "#f1f4dc"
        CF88C49 = "#f88c49"

    def __init__(
        self,
        shape01: Shape01 | str | None = None,
        shape02: Shape02 | str | None = None,
        shape03: Shape03 | str | None = None,
        shape1Color: Shape1Color | str | None = None,
        shape2Color: Shape2Color | str | None = None,
        shape3Color: Shape3Color | str | None = None,
    ) -> None:
        super().__init__(
            shape01=shape01,
            shape02=shape02,
            shape03=shape03,
            shape1Color=shape1Color,
            shape2Color=shape2Color,
            shape3Color=shape3Color,
        )
