# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/shape-grid.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("ShapeGrid",)


@dataclass
class ShapeGrid(StyleBase):
    style_name: ClassVar[str] = "shape-grid"

    rows: Optional[List[str]] = None  # rows01, rows02, rows03, rows04
    shape: Optional[List[str]] = None  # circle, hexagon, plus, polygon, square

    shapeColor: Optional[DColor] = None  # 000000, ffffff
