# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class ShapeGrid(StyleBase):
    _name = "shape-grid"

    class Rows(Enum):
        ROWS01 = "rows01"
        ROWS02 = "rows02"
        ROWS03 = "rows03"
        ROWS04 = "rows04"

    class Shape(Enum):
        CIRCLE = "circle"
        HEXAGON = "hexagon"
        PLUS = "plus"
        POLYGON = "polygon"
        SQUARE = "square"

    class ShapeColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    def __init__(
        self,
        rows: Rows | str | None = None,
        shape: Shape | str | None = None,
        shape01: Shape | str | None = None,
        shape02: Shape | str | None = None,
        shape03: Shape | str | None = None,
        shape04: Shape | str | None = None,
        shape05: Shape | str | None = None,
        shape06: Shape | str | None = None,
        shape07: Shape | str | None = None,
        shape08: Shape | str | None = None,
        shape09: Shape | str | None = None,
        shape10: Shape | str | None = None,
        shape11: Shape | str | None = None,
        shape12: Shape | str | None = None,
        shape13: Shape | str | None = None,
        shape14: Shape | str | None = None,
        shape15: Shape | str | None = None,
        shape16: Shape | str | None = None,
        shapeColor: ShapeColor | str | None = None,
    ) -> None:
        super().__init__(
            rows=rows,
            shape=shape,
            shape01=shape01,
            shape02=shape02,
            shape03=shape03,
            shape04=shape04,
            shape05=shape05,
            shape06=shape06,
            shape07=shape07,
            shape08=shape08,
            shape09=shape09,
            shape10=shape10,
            shape11=shape11,
            shape12=shape12,
            shape13=shape13,
            shape14=shape14,
            shape15=shape15,
            shape16=shape16,
            shapeColor=shapeColor,
        )
