# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/shapes.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Shapes",)


@dataclass
class Shapes(StyleBase):
    style_name: ClassVar[str] = "shapes"

    shape01: Optional[List[str]] = None  # ellipse, ellipseFilled, line, polygon, polygonFilled, ... (2 more)
    shape02: Optional[List[str]] = None  # ellipse, ellipseFilled, line, polygon, polygonFilled, ... (2 more)
    shape03: Optional[List[str]] = None  # ellipse, ellipseFilled, line, polygon, polygonFilled, ... (2 more)

    shape1Color: Optional[DColor] = None  # 0a5b83, 1c799f, 69d2e7, f1f4dc, f88c49
    shape2Color: Optional[DColor] = None  # 0a5b83, 1c799f, 69d2e7, f1f4dc, f88c49
    shape3Color: Optional[DColor] = None  # 0a5b83, 1c799f, 69d2e7, f1f4dc, f88c49
