# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Stripes(StyleBase):
    _name = "stripes"

    class Body(Enum):
        VARIANT05 = "variant05"
        VARIANT10 = "variant10"

    class Stripe(Enum):
        VARIANT02 = "variant02"
        VARIANT04 = "variant04"
        VARIANT06 = "variant06"
        VARIANT08 = "variant08"
        VARIANT10 = "variant10"

    class StripeColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    def __init__(
            self,
            body: Body | str | None = None,
            stripe: Stripe | str | None = None,
            stripe01: Stripe | str | None = None,
            stripe02: Stripe | str | None = None,
            stripe03: Stripe | str | None = None,
            stripe04: Stripe | str | None = None,
            stripe05: Stripe | str | None = None,
            stripe06: Stripe | str | None = None,
            stripe07: Stripe | str | None = None,
            stripe08: Stripe | str | None = None,
            stripe09: Stripe | str | None = None,
            stripe10: Stripe | str | None = None,
            stripe11: Stripe | str | None = None,
            stripe12: Stripe | str | None = None,
            stripe13: Stripe | str | None = None,
            stripe14: Stripe | str | None = None,
            stripeColor: StripeColor | str | None = None,
    ) -> None:
        super().__init__(
            body=body,
            stripe=stripe,
            stripe01=stripe01,
            stripe02=stripe02,
            stripe03=stripe03,
            stripe04=stripe04,
            stripe05=stripe05,
            stripe06=stripe06,
            stripe07=stripe07,
            stripe08=stripe08,
            stripe09=stripe09,
            stripe10=stripe10,
            stripe11=stripe11,
            stripe12=stripe12,
            stripe13=stripe13,
            stripe14=stripe14,
            stripeColor=stripeColor,
        )
