# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/stripes.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Stripes",)


@dataclass
class Stripes(StyleBase):
    style_name: ClassVar[str] = "stripes"

    body: Optional[List[str]] = None  # variant05, variant10
    stripe: Optional[List[str]] = None  # variant02, variant04, variant06, variant08, variant10

    stripeColor: Optional[DColor] = None  # 000000, ffffff
