# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/thumbs.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("Thumbs",)


@dataclass
class Thumbs(StyleBase):
    style_name: ClassVar[str] = "thumbs"

    body: Optional[List[str]] = None  # default
    eyes: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05, ... (3 more)
    head: Optional[List[str]] = None  # default
    mouth: Optional[List[str]] = None  # variant01, variant02, variant03, variant04, variant05

    eyesColor: Optional[DColor] = None  # 000000, ffffff
    mouthColor: Optional[DColor] = None  # 000000, ffffff
    shapeColor: Optional[DColor] = None  # 0a5b83, 1c799f, 69d2e7, f1f4dc, f88c49
