# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Thumbs(StyleBase):
    _name = "thumbs"

    class Body(Enum):
        DEFAULT = "default"

    class Eyes(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"
        VARIANT06 = "variant06"
        VARIANT07 = "variant07"
        VARIANT08 = "variant08"

    class Head(Enum):
        DEFAULT = "default"

    class Mouth(Enum):
        VARIANT01 = "variant01"
        VARIANT02 = "variant02"
        VARIANT03 = "variant03"
        VARIANT04 = "variant04"
        VARIANT05 = "variant05"

    class EyesColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    class MouthColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    class ShapeColor(Enum):
        C0A5B83 = "#0a5b83"
        C1C799F = "#1c799f"
        C69D2E7 = "#69d2e7"
        CF1F4DC = "#f1f4dc"
        CF88C49 = "#f88c49"

    def __init__(
            self,
            body: Body | str | None = None,
            eyes: Eyes | str | None = None,
            head: Head | str | None = None,
            mouth: Mouth | str | None = None,
            eyesColor: EyesColor | str | None = None,
            mouthColor: MouthColor | str | None = None,
            shapeColor: ShapeColor | str | None = None,
    ) -> None:
        super().__init__(
            body=body,
            eyes=eyes,
            head=head,
            mouth=mouth,
            eyesColor=eyesColor,
            mouthColor=mouthColor,
            shapeColor=shapeColor,
        )
