# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class ToonHead(StyleBase):
    _name = "toon-head"

    class Beard(Enum):
        CHIN = "chin"
        CHIN_MOUSTACHE = "chinMoustache"
        FULL_BEARD = "fullBeard"
        LONG_BEARD = "longBeard"
        MOUSTACHE_TWIRL = "moustacheTwirl"

    class Body(Enum):
        BODY = "body"

    class Clothes(Enum):
        DRESS = "dress"
        OPEN_JACKET = "openJacket"
        SHIRT = "shirt"
        T_SHIRT = "tShirt"
        TURTLE_NECK = "turtleNeck"

    class Eyebrows(Enum):
        ANGRY = "angry"
        HAPPY = "happy"
        NEUTRAL = "neutral"
        RAISED = "raised"
        SAD = "sad"

    class Eyes(Enum):
        BOW = "bow"
        HAPPY = "happy"
        HUMBLE = "humble"
        WIDE = "wide"
        WINK = "wink"

    class Hair(Enum):
        BUN = "bun"
        SIDE_COMED = "sideComed"
        SPIKY = "spiky"
        UNDERCUT = "undercut"

    class Head(Enum):
        HEAD = "head"

    class Mouth(Enum):
        AGAPE = "agape"
        ANGRY = "angry"
        LAUGH = "laugh"
        SAD = "sad"
        SMILE = "smile"

    class RearHair(Enum):
        LONG_STRAIGHT = "longStraight"
        LONG_WAVY = "longWavy"
        NECK_HIGH = "neckHigh"
        SHOULDER_HIGH = "shoulderHigh"

    class ClothesColor(Enum):
        C151613 = "#151613"
        C0B3286 = "#0b3286"
        C545454 = "#545454"
        C147F3C = "#147f3c"
        CF97316 = "#f97316"
        CEC4899 = "#ec4899"
        C731AC3 = "#731ac3"
        CB11F1F = "#b11f1f"
        CE8E9E6 = "#e8e9e6"
        CEAB308 = "#eab308"

    class HairColor(Enum):
        C2C1B18 = "#2c1b18"
        CD6B370 = "#d6b370"
        C724133 = "#724133"
        CA55728 = "#a55728"
        CB58143 = "#b58143"

    class SkinColor(Enum):
        C5C3829 = "#5c3829"
        CF1C3A5 = "#f1c3a5"
        CA36B4F = "#a36b4f"
        CC68E7A = "#c68e7a"
        CB98E6A = "#b98e6a"

    def __init__(
        self,
        beard: Beard | str | None = None,
        beardProbability: int | None = None,
        body: Body | str | None = None,
        clothes: Clothes | str | None = None,
        eyebrows: Eyebrows | str | None = None,
        eyes: Eyes | str | None = None,
        hair: Hair | str | None = None,
        hairProbability: int | None = None,
        head: Head | str | None = None,
        mouth: Mouth | str | None = None,
        rearHair: RearHair | str | None = None,
        rearHairProbability: int | None = None,
        clothesColor: ClothesColor | str | None = None,
        hairColor: HairColor | str | None = None,
        skinColor: SkinColor | str | None = None,
    ) -> None:
        super().__init__(
            beard=beard,
            beardProbability=beardProbability,
            body=body,
            clothes=clothes,
            eyebrows=eyebrows,
            eyes=eyes,
            hair=hair,
            hairProbability=hairProbability,
            head=head,
            mouth=mouth,
            rearHair=rearHair,
            rearHairProbability=rearHairProbability,
            clothesColor=clothesColor,
            hairColor=hairColor,
            skinColor=skinColor,
        )
