# GENERATED by scripts/generate.py — do not edit manually
# Source: https://github.com/dicebear/styles/blob/main/src/toon-head.json
from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, Optional, List

from ..models import DColor
from ._base import StyleBase

__all__ = ("ToonHead",)


@dataclass
class ToonHead(StyleBase):
    style_name: ClassVar[str] = "toon-head"

    beard: Optional[List[str]] = None  # chin, chinMoustache, fullBeard, longBeard, moustacheTwirl
    body: Optional[List[str]] = None  # body
    clothes: Optional[List[str]] = None  # dress, openJacket, shirt, tShirt, turtleNeck
    eyebrows: Optional[List[str]] = None  # angry, happy, neutral, raised, sad
    eyes: Optional[List[str]] = None  # bow, happy, humble, wide, wink
    hair: Optional[List[str]] = None  # bun, sideComed, spiky, undercut
    head: Optional[List[str]] = None  # head
    mouth: Optional[List[str]] = None  # agape, angry, laugh, sad, smile
    rearHair: Optional[List[str]] = None  # longStraight, longWavy, neckHigh, shoulderHigh

    clothesColor: Optional[DColor] = None  # 151613, 0b3286, 545454, 147f3c, f97316, ... (5 more)
    hairColor: Optional[DColor] = None  # 2c1b18, d6b370, 724133, a55728, b58143
    skinColor: Optional[DColor] = None  # 5c3829, f1c3a5, a36b4f, c68e7a, b98e6a
