# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually
# Source: dicebear-styles 10.1.0rc1
from __future__ import annotations

from enum import Enum

from ._style import StyleBase


class Triangles(StyleBase):
    _name = "triangles"

    class Body(Enum):
        DEFAULT = "default"

    class Shape(Enum):
        TRIANGLE = "triangle"

    class ShapeColor(Enum):
        C000000 = "#000000"
        CFFFFFF = "#ffffff"

    def __init__(
        self,
        body: Body | str | None = None,
        shape: Shape | str | None = None,
        shape01: Shape | str | None = None,
        shape02: Shape | str | None = None,
        shape03: Shape | str | None = None,
        shape04: Shape | str | None = None,
        shape05: Shape | str | None = None,
        shape06: Shape | str | None = None,
        shape07: Shape | str | None = None,
        shape08: Shape | str | None = None,
        shape09: Shape | str | None = None,
        shape10: Shape | str | None = None,
        shape11: Shape | str | None = None,
        shape12: Shape | str | None = None,
        shape13: Shape | str | None = None,
        shape14: Shape | str | None = None,
        shape15: Shape | str | None = None,
        shape16: Shape | str | None = None,
        shape17: Shape | str | None = None,
        shape18: Shape | str | None = None,
        shape19: Shape | str | None = None,
        shape20: Shape | str | None = None,
        shape21: Shape | str | None = None,
        shape22: Shape | str | None = None,
        shape23: Shape | str | None = None,
        shape24: Shape | str | None = None,
        shape25: Shape | str | None = None,
        shape26: Shape | str | None = None,
        shape27: Shape | str | None = None,
        shape28: Shape | str | None = None,
        shape29: Shape | str | None = None,
        shape30: Shape | str | None = None,
        shape31: Shape | str | None = None,
        shape32: Shape | str | None = None,
        shape33: Shape | str | None = None,
        shape34: Shape | str | None = None,
        shape35: Shape | str | None = None,
        shape36: Shape | str | None = None,
        shapeColor: ShapeColor | str | None = None,
    ) -> None:
        super().__init__(
            body=body,
            shape=shape,
            shape01=shape01,
            shape02=shape02,
            shape03=shape03,
            shape04=shape04,
            shape05=shape05,
            shape06=shape06,
            shape07=shape07,
            shape08=shape08,
            shape09=shape09,
            shape10=shape10,
            shape11=shape11,
            shape12=shape12,
            shape13=shape13,
            shape14=shape14,
            shape15=shape15,
            shape16=shape16,
            shape17=shape17,
            shape18=shape18,
            shape19=shape19,
            shape20=shape20,
            shape21=shape21,
            shape22=shape22,
            shape23=shape23,
            shape24=shape24,
            shape25=shape25,
            shape26=shape26,
            shape27=shape27,
            shape28=shape28,
            shape29=shape29,
            shape30=shape30,
            shape31=shape31,
            shape32=shape32,
            shape33=shape33,
            shape34=shape34,
            shape35=shape35,
            shape36=shape36,
            shapeColor=shapeColor,
        )
