"""
Generates typed Python style classes from DiceBear style definition JSONs
and regenerates src/dicebear/styles/__init__.py.

Usage: python scripts/generate.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

SCHEMAS_DIR = Path(__file__).parent.parent / "src" / "dicebear" / "styles" / "schemas"
STYLES_DIR = Path(__file__).parent.parent / "src" / "dicebear" / "styles"

# Colors that map to base DOptions — skip in generated classes
BASE_COLORS = {"background"}


def to_class_name(style_name: str) -> str:
    """adventurer-neutral → AdventurerNeutral"""
    return "".join(word.title() for word in style_name.split("-"))


def to_module_name(style_name: str) -> str:
    """adventurer-neutral → adventurer_neutral"""
    return style_name.replace("-", "_")


def extract_components(schema: dict) -> list[tuple[str, list[str]]]:
    """(component_name, [variant_names]) for each non-alias component."""
    result = []
    for name, defn in schema.get("components", {}).items():
        if "extends" in defn:
            continue
        variants = list(defn.get("variants", {}).keys())
        result.append((name, variants))
    return result


def extract_colors(schema: dict) -> list[tuple[str, list[str]]]:
    """(field_name, [hex_values]) for each non-base color."""
    result = []
    for key, defn in schema.get("colors", {}).items():
        if key in BASE_COLORS:
            continue
        field_name = key if key.lower().endswith("color") else f"{key}Color"
        values = [v.lstrip("#") for v in defn.get("values", [])]
        result.append((field_name, values))
    return result


def fmt_values(values: list[str], max_show: int = 5) -> str:
    if not values:
        return ""
    shown = ", ".join(values[:max_show])
    remaining = len(values) - max_show
    return shown + (f", ... ({remaining} more)" if remaining > 0 else "")


def generate_style_file(style_name: str, schema: dict) -> str:
    class_name = to_class_name(style_name)
    components = extract_components(schema)
    colors = extract_colors(schema)
    needs_list = bool(components)
    needs_dcolor = bool(colors)

    lines = [
        "# GENERATED by scripts/generate.py — do not edit manually",
        f"# Source: https://github.com/dicebear/styles/blob/main/src/{style_name}.json",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import ClassVar, Optional" + (", List" if needs_list else ""),
        "",
    ]

    if needs_dcolor:
        lines.append("from ..models import DColor")
    lines += [
        "from ._base import StyleBase",
        "",
        f'__all__ = ("{class_name}",)',
        "",
        "",
        "@dataclass",
        f"class {class_name}(StyleBase):",
        f'    style_name: ClassVar[str] = "{style_name}"',
    ]

    if not components and not colors:
        lines.append("    pass")
    else:
        if components:
            lines.append("")
            for comp_name, variants in components:
                comment = fmt_values(variants)
                line = f"    {comp_name}: Optional[List[str]] = None"
                if comment:
                    line += f"  # {comment}"
                lines.append(line)
        if colors:
            lines.append("")
            for field_name, values in colors:
                comment = fmt_values(values)
                line = f"    {field_name}: Optional[DColor] = None"
                if comment:
                    line += f"  # {comment}"
                lines.append(line)

    lines.append("")
    return "\n".join(lines)


def generate_init(entries: list[tuple[str, str]]) -> str:
    """entries: [(module_name, class_name), ...]"""
    lines = [
        "# GENERATED by scripts/generate.py — do not edit manually",
        "from __future__ import annotations",
        "",
        "from ._base import StyleBase",
        "",
    ]
    for module_name, class_name in entries:
        lines.append(f"from .{module_name} import {class_name}")

    all_names = ["StyleBase"] + [class_name for _, class_name in entries]
    all_items = ",\n    ".join(f'"{n}"' for n in all_names)
    lines += [
        "",
        f"__all__ = [\n    {all_items},\n]",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    if not SCHEMAS_DIR.exists():
        print(f"Schemas directory not found: {SCHEMAS_DIR}")
        print("Run scripts/fetch_schemas.py first.")
        return 1

    json_files = sorted(SCHEMAS_DIR.glob("*.json"))
    if not json_files:
        print("No JSON files found in schemas directory.")
        return 1

    entries: list[tuple[str, str]] = []

    for json_path in json_files:
        style_name = json_path.stem
        module_name = to_module_name(style_name)
        class_name = to_class_name(style_name)

        schema = json.loads(json_path.read_text(encoding="utf-8"))
        content = generate_style_file(style_name, schema)

        out_path = STYLES_DIR / f"{module_name}.py"
        out_path.write_text(content, encoding="utf-8")
        print(f"  Generated {out_path.name}")

        entries.append((module_name, class_name))

    init_path = STYLES_DIR / "__init__.py"
    init_path.write_text(generate_init(entries), encoding="utf-8")
    print(f"  Regenerated __init__.py")
    print(f"\nDone. {len(entries)} style files generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
