"""
Generate typed Python style classes from the installed dicebear-styles package.

Each generated class has:
  - Nested Enum classes for every component (variant names as SCREAMING_SNAKE_CASE)
  - Nested Enum classes for every non-background color (hex values as CHHHHHH)
  - A fully typed __init__ with one param per component / probability / color
  - Component aliases (extends) share the source Enum — no duplicate enums
  - Inherits StyleBase from dicebear._style

Usage:
    python scripts/generate_styles.py             # generate all styles + __init__.py
    python scripts/generate_styles.py avataaars   # generate one style for preview
"""

from __future__ import annotations

import json
import re
import sys
from importlib.metadata import version
from importlib.resources import files
from pathlib import Path

STYLES_DIR = Path(__file__).parent.parent / "src" / "dicebear" / "styles"
SKIP_COLORS = {"background"}


# ---------------------------------------------------------------------------
# Name conversion helpers
# ---------------------------------------------------------------------------

def _styles_version() -> str:
    try:
        return version("dicebear-styles")
    except Exception:
        return "unknown"


def style_to_class_name(style_name: str) -> str:
    """pixel-art → PixelArt, avataaars → Avataaars"""
    return "".join(w.title() for w in style_name.split("-"))


def style_to_module_name(style_name: str) -> str:
    """pixel-art → pixel_art"""
    return style_name.replace("-", "_")


def camel_to_screaming_snake(name: str) -> str:
    """
    longCurly → LONG_CURLY
    variant01  → VARIANT01
    angryNatural → ANGRY_NATURAL
    """
    s = re.sub(r'([a-z\d])([A-Z])', r'\1_\2', name)
    return s.upper()


def component_to_class_name(comp_name: str) -> str:
    """eyes → Eyes, skinColor → SkinColor"""
    return comp_name[0].upper() + comp_name[1:]


def color_key_to_param_name(key: str) -> str:
    """skin → skinColor, accessories → accessoriesColor, hairColor → hairColor"""
    if key.lower().endswith("color"):
        return key
    return key + "Color"


def color_key_to_class_name(key: str) -> str:
    """skin → SkinColor, accessories → AccessoriesColor"""
    param = color_key_to_param_name(key)
    return param[0].upper() + param[1:]


def hex_to_enum_member(hex_val: str) -> str:
    """#65c9ff → C65C9FF (prefix C so the name is a valid identifier)"""
    return "C" + hex_val.lstrip("#").upper()


# ---------------------------------------------------------------------------
# Style discovery
# ---------------------------------------------------------------------------

def iter_style_names() -> list[str]:
    pkg = files("dicebear_styles")
    return sorted(
        str(f).split("/")[-1].replace(".json", "")
        for f in pkg.iterdir()
        if str(f).endswith(".json")
    )


def load_schema(style_name: str) -> dict:
    return json.loads(
        files("dicebear_styles").joinpath(f"{style_name}.json").read_text("utf-8")
    )


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def generate_style_source(style_name: str, schema: dict, ver: str) -> str:
    class_name = style_to_class_name(style_name)
    components = schema.get("components", {})
    colors = schema.get("colors", {})

    base_comps = {
        name: defn for name, defn in components.items() if "extends" not in defn
    }
    alias_comps = {
        name: defn for name, defn in components.items() if "extends" in defn
    }
    color_items = [
        (key, defn) for key, defn in colors.items() if key not in SKIP_COLORS
    ]

    lines: list[str] = [
        "# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually",
        f"# Source: dicebear-styles {ver}",
        "from __future__ import annotations",
        "",
        "from enum import Enum",
        "",
        "from ._style import StyleBase",
        "",
        "",
        f"class {class_name}(StyleBase):",
        f'    _name = "{style_name}"',
    ]

    # Enum classes for base components (variants → SCREAMING_SNAKE members)
    for comp_name, defn in base_comps.items():
        variants = list(defn.get("variants", {}).keys())
        if not variants:
            continue
        enum_class = component_to_class_name(comp_name)
        lines += ["", f"    class {enum_class}(Enum):"]
        for v in variants:
            lines.append(f'        {camel_to_screaming_snake(v)} = "{v}"')

    # Enum classes for non-background colors (hex values → CHHHHHH members)
    for color_key, color_defn in color_items:
        values = color_defn.get("values", [])
        if not values:
            continue
        enum_class = color_key_to_class_name(color_key)
        lines += ["", f"    class {enum_class}(Enum):"]
        for v in values:
            lines.append(f'        {hex_to_enum_member(v)} = "{v}"')

    # Build __init__ param list and matching super().__init__() kwargs
    params: list[str] = []
    super_kwargs: list[str] = []

    # Base components (each optionally followed by its probability param)
    for comp_name, defn in base_comps.items():
        variants = list(defn.get("variants", {}).keys())
        if variants:
            enum_class = component_to_class_name(comp_name)
            params.append(f"{comp_name}: {enum_class} | str | None = None")
        else:
            params.append(f"{comp_name}: str | None = None")
        super_kwargs.append(comp_name)
        if "probability" in defn:
            params.append(f"{comp_name}Probability: int | None = None")
            super_kwargs.append(f"{comp_name}Probability")

    # Alias components — reuse the source Enum, never generate a duplicate
    for comp_name, defn in alias_comps.items():
        source = defn["extends"]
        source_variants = list(base_comps.get(source, {}).get("variants", {}).keys())
        if source_variants:
            source_class = component_to_class_name(source)
            params.append(f"{comp_name}: {source_class} | str | None = None")
        else:
            params.append(f"{comp_name}: str | None = None")
        super_kwargs.append(comp_name)

    # Colors
    for color_key, color_defn in color_items:
        values = color_defn.get("values", [])
        param_name = color_key_to_param_name(color_key)
        if values:
            enum_class = color_key_to_class_name(color_key)
            params.append(f"{param_name}: {enum_class} | str | None = None")
        else:
            params.append(f"{param_name}: str | None = None")
        super_kwargs.append(param_name)

    # __init__ method
    lines.append("")
    if not params:
        lines += [
            "    def __init__(self) -> None:",
            "        super().__init__()",
        ]
    else:
        lines.append("    def __init__(")
        lines.append("        self,")
        for p in params:
            lines.append(f"        {p},")
        lines.append("    ) -> None:")
        lines.append("        super().__init__(")
        for kw in super_kwargs:
            lines.append(f"            {kw}={kw},")
        lines.append("        )")

    lines.append("")
    return "\n".join(lines)


def generate_init_source(entries: list[tuple[str, str]], ver: str) -> str:
    lines = [
        "# AUTO-GENERATED by scripts/generate_styles.py — do not edit manually",
        f"# Source: dicebear-styles {ver}",
        "from __future__ import annotations",
        "",
        "from ._style import StyleBase",
        "",
    ]
    for module_name, class_name in entries:
        lines.append(f"from .{module_name} import {class_name}")

    all_names = ["StyleBase"] + [cn for _, cn in entries]
    all_items = ",\n    ".join(f'"{n}"' for n in all_names)
    lines += [
        "",
        f"__all__ = [\n    {all_items},\n]",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    ver = _styles_version()
    target_style = sys.argv[1] if len(sys.argv) > 1 else None

    style_names = [target_style] if target_style else iter_style_names()

    entries: list[tuple[str, str]] = []
    for style_name in style_names:
        module_name = style_to_module_name(style_name)
        class_name = style_to_class_name(style_name)
        schema = load_schema(style_name)
        source = generate_style_source(style_name, schema, ver)
        out_path = STYLES_DIR / f"{module_name}.py"
        out_path.write_text(source, encoding="utf-8")
        print(f"  Generated {out_path.name}")
        entries.append((module_name, class_name))

    if not target_style:
        init_source = generate_init_source(entries, ver)
        init_path = STYLES_DIR / "__init__.py"
        init_path.write_text(init_source, encoding="utf-8")
        print(f"  Regenerated __init__.py")
        print(f"\nDone. {len(entries)} style files generated.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
